// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 77ddf656afdc

package operations

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/shared"
	"net/http"
)

type CreateOrUpdateAPILinkGlobals struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
}

func (c CreateOrUpdateAPILinkGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOrUpdateAPILinkGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOrUpdateAPILinkGlobals) GetOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationID
}

func (c *CreateOrUpdateAPILinkGlobals) GetEnvironmentID() *string {
	if c == nil {
		return nil
	}
	return c.EnvironmentID
}

type CreateOrUpdateAPILinkRequest struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
	// Human-readable ID of api
	APIHrid string `pathParam:"style=simple,explode=false,name=apiHrid"`
	// For modifying requests, this parameter allow you to test the result of an endpoint without actually persisting
	// the state of the underlying spec.
	//
	DryRun *bool `default:"false" queryParam:"style=form,explode=true,name=dryRun"`
	// Portal Link specification
	PortalLinkSpec shared.PortalLinkSpec `request:"mediaType=application/json"`
}

func (c CreateOrUpdateAPILinkRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOrUpdateAPILinkRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOrUpdateAPILinkRequest) GetOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationID
}

func (c *CreateOrUpdateAPILinkRequest) GetEnvironmentID() *string {
	if c == nil {
		return nil
	}
	return c.EnvironmentID
}

func (c *CreateOrUpdateAPILinkRequest) GetAPIHrid() string {
	if c == nil {
		return ""
	}
	return c.APIHrid
}

func (c *CreateOrUpdateAPILinkRequest) GetDryRun() *bool {
	if c == nil {
		return nil
	}
	return c.DryRun
}

func (c *CreateOrUpdateAPILinkRequest) GetPortalLinkSpec() shared.PortalLinkSpec {
	if c == nil {
		return shared.PortalLinkSpec{}
	}
	return c.PortalLinkSpec
}

type CreateOrUpdateAPILinkResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// State of the successfully created/updated Link
	PortalLinkSpec *shared.PortalLinkSpec
	// Request is invalid
	HTTPError *shared.HTTPError
	// Default error
	Error *shared.Error
}

func (c *CreateOrUpdateAPILinkResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateOrUpdateAPILinkResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateOrUpdateAPILinkResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateOrUpdateAPILinkResponse) GetPortalLinkSpec() *shared.PortalLinkSpec {
	if c == nil {
		return nil
	}
	return c.PortalLinkSpec
}

func (c *CreateOrUpdateAPILinkResponse) GetHTTPError() *shared.HTTPError {
	if c == nil {
		return nil
	}
	return c.HTTPError
}

func (c *CreateOrUpdateAPILinkResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
