// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7965fbfab437

package operations

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/shared"
	"net/http"
)

type CreateOrUpdatePortalThemeGlobals struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
}

func (c CreateOrUpdatePortalThemeGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOrUpdatePortalThemeGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOrUpdatePortalThemeGlobals) GetOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationID
}

func (c *CreateOrUpdatePortalThemeGlobals) GetEnvironmentID() *string {
	if c == nil {
		return nil
	}
	return c.EnvironmentID
}

type CreateOrUpdatePortalThemeRequest struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
	// For modifying requests, this parameter allow you to test the result of an endpoint without actually persisting
	// the state of the underlying spec.
	//
	DryRun *bool `default:"false" queryParam:"style=form,explode=true,name=dryRun"`
	// Theme specification
	PortalThemeSpec shared.PortalThemeSpec `request:"mediaType=application/json"`
}

func (c CreateOrUpdatePortalThemeRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOrUpdatePortalThemeRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOrUpdatePortalThemeRequest) GetOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationID
}

func (c *CreateOrUpdatePortalThemeRequest) GetEnvironmentID() *string {
	if c == nil {
		return nil
	}
	return c.EnvironmentID
}

func (c *CreateOrUpdatePortalThemeRequest) GetDryRun() *bool {
	if c == nil {
		return nil
	}
	return c.DryRun
}

func (c *CreateOrUpdatePortalThemeRequest) GetPortalThemeSpec() shared.PortalThemeSpec {
	if c == nil {
		return shared.PortalThemeSpec{}
	}
	return c.PortalThemeSpec
}

type CreateOrUpdatePortalThemeResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// State of the successfully created/updated Theme
	PortalThemeState *shared.PortalThemeState
	// Request is invalid
	HTTPError *shared.HTTPError
	// Default error
	Error *shared.Error
}

func (c *CreateOrUpdatePortalThemeResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateOrUpdatePortalThemeResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateOrUpdatePortalThemeResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateOrUpdatePortalThemeResponse) GetPortalThemeState() *shared.PortalThemeState {
	if c == nil {
		return nil
	}
	return c.PortalThemeState
}

func (c *CreateOrUpdatePortalThemeResponse) GetHTTPError() *shared.HTTPError {
	if c == nil {
		return nil
	}
	return c.HTTPError
}

func (c *CreateOrUpdatePortalThemeResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
