// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 12af20c4aeb9

package operations

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/shared"
	"net/http"
)

type CreateOrUpdateGroupGlobals struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
}

func (c CreateOrUpdateGroupGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOrUpdateGroupGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOrUpdateGroupGlobals) GetOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationID
}

func (c *CreateOrUpdateGroupGlobals) GetEnvironmentID() *string {
	if c == nil {
		return nil
	}
	return c.EnvironmentID
}

type CreateOrUpdateGroupRequest struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
	// For modifying requests, this parameter allow you to test the result of an endpoint without actually persisting
	// the state of the underlying spec.
	//
	DryRun *bool `default:"false" queryParam:"style=form,explode=true,name=dryRun"`
	// When true, the HRID path or spec value is treated as an existing UUID rather than
	// a human-readable identifier. This is to support backward compatibility for resources
	// created before migration to the automation API and should not be used for new resources.
	//
	HridContainsUUID *bool `default:"false" queryParam:"style=form,explode=true,name=hridContainsUUID"`
	// Group specification
	GroupSpec shared.GroupSpec `request:"mediaType=application/json"`
}

func (c CreateOrUpdateGroupRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOrUpdateGroupRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOrUpdateGroupRequest) GetOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationID
}

func (c *CreateOrUpdateGroupRequest) GetEnvironmentID() *string {
	if c == nil {
		return nil
	}
	return c.EnvironmentID
}

func (c *CreateOrUpdateGroupRequest) GetDryRun() *bool {
	if c == nil {
		return nil
	}
	return c.DryRun
}

func (c *CreateOrUpdateGroupRequest) GetHridContainsUUID() *bool {
	if c == nil {
		return nil
	}
	return c.HridContainsUUID
}

func (c *CreateOrUpdateGroupRequest) GetGroupSpec() shared.GroupSpec {
	if c == nil {
		return shared.GroupSpec{}
	}
	return c.GroupSpec
}

type CreateOrUpdateGroupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// State of the successfully created/updated Group
	GroupState *shared.GroupState
	// Request is invalid
	HTTPError *shared.HTTPError
	// Default error
	Error *shared.Error
}

func (c *CreateOrUpdateGroupResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateOrUpdateGroupResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateOrUpdateGroupResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateOrUpdateGroupResponse) GetGroupState() *shared.GroupState {
	if c == nil {
		return nil
	}
	return c.GroupState
}

func (c *CreateOrUpdateGroupResponse) GetHTTPError() *shared.HTTPError {
	if c == nil {
		return nil
	}
	return c.HTTPError
}

func (c *CreateOrUpdateGroupResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
