// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2f38417a3f04

package operations

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/shared"
	"net/http"
)

type CreateOrUpdateAPIMockDocumentGlobals struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
}

func (c CreateOrUpdateAPIMockDocumentGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOrUpdateAPIMockDocumentGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOrUpdateAPIMockDocumentGlobals) GetOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationID
}

func (c *CreateOrUpdateAPIMockDocumentGlobals) GetEnvironmentID() *string {
	if c == nil {
		return nil
	}
	return c.EnvironmentID
}

type CreateOrUpdateAPIMockDocumentRequest struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
	// Human-readable ID of api
	APIHrid string `pathParam:"style=simple,explode=false,name=apiHrid"`
	// Document specification
	DocumentSpec shared.DocumentSpec `request:"mediaType=application/json"`
}

func (c CreateOrUpdateAPIMockDocumentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOrUpdateAPIMockDocumentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOrUpdateAPIMockDocumentRequest) GetOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationID
}

func (c *CreateOrUpdateAPIMockDocumentRequest) GetEnvironmentID() *string {
	if c == nil {
		return nil
	}
	return c.EnvironmentID
}

func (c *CreateOrUpdateAPIMockDocumentRequest) GetAPIHrid() string {
	if c == nil {
		return ""
	}
	return c.APIHrid
}

func (c *CreateOrUpdateAPIMockDocumentRequest) GetDocumentSpec() shared.DocumentSpec {
	if c == nil {
		return shared.DocumentSpec{}
	}
	return c.DocumentSpec
}

type CreateOrUpdateAPIMockDocumentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Document successfully created/updated
	DocumentState *shared.DocumentState
	// Request is invalid
	HTTPError *shared.HTTPError
	// Default error
	Error *shared.Error
}

func (c *CreateOrUpdateAPIMockDocumentResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateOrUpdateAPIMockDocumentResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateOrUpdateAPIMockDocumentResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateOrUpdateAPIMockDocumentResponse) GetDocumentState() *shared.DocumentState {
	if c == nil {
		return nil
	}
	return c.DocumentState
}

func (c *CreateOrUpdateAPIMockDocumentResponse) GetHTTPError() *shared.HTTPError {
	if c == nil {
		return nil
	}
	return c.HTTPError
}

func (c *CreateOrUpdateAPIMockDocumentResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
