// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/shared"
	"net/http"
)

type CreateOrUpdateAPISubscriptionsGlobals struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
}

func (c CreateOrUpdateAPISubscriptionsGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOrUpdateAPISubscriptionsGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOrUpdateAPISubscriptionsGlobals) GetOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationID
}

func (c *CreateOrUpdateAPISubscriptionsGlobals) GetEnvironmentID() *string {
	if c == nil {
		return nil
	}
	return c.EnvironmentID
}

type CreateOrUpdateAPISubscriptionsRequest struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
	// Human-readable ID of api
	APIHrid string `pathParam:"style=simple,explode=false,name=apiHrid"`
	// Subscription specification
	SubscriptionSpec shared.SubscriptionSpec `request:"mediaType=application/json"`
}

func (c CreateOrUpdateAPISubscriptionsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOrUpdateAPISubscriptionsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"apiHrid", "SubscriptionSpec"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateOrUpdateAPISubscriptionsRequest) GetOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationID
}

func (c *CreateOrUpdateAPISubscriptionsRequest) GetEnvironmentID() *string {
	if c == nil {
		return nil
	}
	return c.EnvironmentID
}

func (c *CreateOrUpdateAPISubscriptionsRequest) GetAPIHrid() string {
	if c == nil {
		return ""
	}
	return c.APIHrid
}

func (c *CreateOrUpdateAPISubscriptionsRequest) GetSubscriptionSpec() shared.SubscriptionSpec {
	if c == nil {
		return shared.SubscriptionSpec{}
	}
	return c.SubscriptionSpec
}

type CreateOrUpdateAPISubscriptionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// State of the successfully created Subscription
	SubscriptionState *shared.SubscriptionState
	// Request is invalid
	HTTPError *shared.HTTPError
	// Default error
	Error *shared.Error
}

func (c *CreateOrUpdateAPISubscriptionsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateOrUpdateAPISubscriptionsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateOrUpdateAPISubscriptionsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateOrUpdateAPISubscriptionsResponse) GetSubscriptionState() *shared.SubscriptionState {
	if c == nil {
		return nil
	}
	return c.SubscriptionState
}

func (c *CreateOrUpdateAPISubscriptionsResponse) GetHTTPError() *shared.HTTPError {
	if c == nil {
		return nil
	}
	return c.HTTPError
}

func (c *CreateOrUpdateAPISubscriptionsResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
