// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/shared"
	"net/http"
)

type CreateOrUpdateApplicationsGlobals struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
}

func (c CreateOrUpdateApplicationsGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOrUpdateApplicationsGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOrUpdateApplicationsGlobals) GetOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationID
}

func (c *CreateOrUpdateApplicationsGlobals) GetEnvironmentID() *string {
	if c == nil {
		return nil
	}
	return c.EnvironmentID
}

type CreateOrUpdateApplicationsRequest struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
	// For modifying requests, this parameter allow you to test the result of an endpoint without actually persisting
	// the state of the underlying spec.
	//
	DryRun *bool `default:"false" queryParam:"style=form,explode=true,name=dryRun"`
	// Application specification
	ApplicationSpec shared.ApplicationSpec `request:"mediaType=application/json"`
}

func (c CreateOrUpdateApplicationsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOrUpdateApplicationsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOrUpdateApplicationsRequest) GetOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationID
}

func (c *CreateOrUpdateApplicationsRequest) GetEnvironmentID() *string {
	if c == nil {
		return nil
	}
	return c.EnvironmentID
}

func (c *CreateOrUpdateApplicationsRequest) GetDryRun() *bool {
	if c == nil {
		return nil
	}
	return c.DryRun
}

func (c *CreateOrUpdateApplicationsRequest) GetApplicationSpec() shared.ApplicationSpec {
	if c == nil {
		return shared.ApplicationSpec{}
	}
	return c.ApplicationSpec
}

type CreateOrUpdateApplicationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// State of the successfully created/updated Applications
	ApplicationState *shared.ApplicationState
	// Request is invalid
	HTTPError *shared.HTTPError
	// Default error
	Error *shared.Error
}

func (c *CreateOrUpdateApplicationsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateOrUpdateApplicationsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateOrUpdateApplicationsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateOrUpdateApplicationsResponse) GetApplicationState() *shared.ApplicationState {
	if c == nil {
		return nil
	}
	return c.ApplicationState
}

func (c *CreateOrUpdateApplicationsResponse) GetHTTPError() *shared.HTTPError {
	if c == nil {
		return nil
	}
	return c.HTTPError
}

func (c *CreateOrUpdateApplicationsResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
