// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b1eabf711d90

package operations

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/shared"
	"net/http"
)

type DeleteApplicationMockDocumentGlobals struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
}

func (d DeleteApplicationMockDocumentGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteApplicationMockDocumentGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteApplicationMockDocumentGlobals) GetOrganizationID() *string {
	if d == nil {
		return nil
	}
	return d.OrganizationID
}

func (d *DeleteApplicationMockDocumentGlobals) GetEnvironmentID() *string {
	if d == nil {
		return nil
	}
	return d.EnvironmentID
}

type DeleteApplicationMockDocumentRequest struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
	// Human-readable ID of application
	AppHrid string `pathParam:"style=simple,explode=false,name=appHrid"`
	// Human-readable ID of a spec
	Hrid string `pathParam:"style=simple,explode=false,name=hrid"`
}

func (d DeleteApplicationMockDocumentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteApplicationMockDocumentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteApplicationMockDocumentRequest) GetOrganizationID() *string {
	if d == nil {
		return nil
	}
	return d.OrganizationID
}

func (d *DeleteApplicationMockDocumentRequest) GetEnvironmentID() *string {
	if d == nil {
		return nil
	}
	return d.EnvironmentID
}

func (d *DeleteApplicationMockDocumentRequest) GetAppHrid() string {
	if d == nil {
		return ""
	}
	return d.AppHrid
}

func (d *DeleteApplicationMockDocumentRequest) GetHrid() string {
	if d == nil {
		return ""
	}
	return d.Hrid
}

type DeleteApplicationMockDocumentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Resource not found
	HTTPError *shared.HTTPError
	// Default error
	Error *shared.Error
}

func (d *DeleteApplicationMockDocumentResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteApplicationMockDocumentResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteApplicationMockDocumentResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteApplicationMockDocumentResponse) GetHTTPError() *shared.HTTPError {
	if d == nil {
		return nil
	}
	return d.HTTPError
}

func (d *DeleteApplicationMockDocumentResponse) GetError() *shared.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
