// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7e11b9f22aca

package operations

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/shared"
	"net/http"
)

type DeletePolicyGroupGlobals struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
}

func (d DeletePolicyGroupGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeletePolicyGroupGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeletePolicyGroupGlobals) GetOrganizationID() *string {
	if d == nil {
		return nil
	}
	return d.OrganizationID
}

func (d *DeletePolicyGroupGlobals) GetEnvironmentID() *string {
	if d == nil {
		return nil
	}
	return d.EnvironmentID
}

type DeletePolicyGroupRequest struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
	// Human-readable ID of a spec
	Hrid string `pathParam:"style=simple,explode=false,name=hrid"`
	// For modifying requests, this parameter allow you to test the result of an endpoint without actually persisting
	// the state of the underlying spec.
	//
	DryRun *bool `default:"false" queryParam:"style=form,explode=true,name=dryRun"`
}

func (d DeletePolicyGroupRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeletePolicyGroupRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeletePolicyGroupRequest) GetOrganizationID() *string {
	if d == nil {
		return nil
	}
	return d.OrganizationID
}

func (d *DeletePolicyGroupRequest) GetEnvironmentID() *string {
	if d == nil {
		return nil
	}
	return d.EnvironmentID
}

func (d *DeletePolicyGroupRequest) GetHrid() string {
	if d == nil {
		return ""
	}
	return d.Hrid
}

func (d *DeletePolicyGroupRequest) GetDryRun() *bool {
	if d == nil {
		return nil
	}
	return d.DryRun
}

type DeletePolicyGroupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthenticated
	HTTPError *shared.HTTPError
	// Default error
	Error *shared.Error
}

func (d *DeletePolicyGroupResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeletePolicyGroupResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeletePolicyGroupResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeletePolicyGroupResponse) GetHTTPError() *shared.HTTPError {
	if d == nil {
		return nil
	}
	return d.HTTPError
}

func (d *DeletePolicyGroupResponse) GetError() *shared.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
