// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: fcb609e55995

package operations

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/shared"
	"net/http"
)

type DeleteAimCatalogMcpServerGlobals struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
}

func (d DeleteAimCatalogMcpServerGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteAimCatalogMcpServerGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteAimCatalogMcpServerGlobals) GetOrganizationID() *string {
	if d == nil {
		return nil
	}
	return d.OrganizationID
}

func (d *DeleteAimCatalogMcpServerGlobals) GetEnvironmentID() *string {
	if d == nil {
		return nil
	}
	return d.EnvironmentID
}

type DeleteAimCatalogMcpServerRequest struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
	// Human-readable ID of a spec
	Hrid string `pathParam:"style=simple,explode=false,name=hrid"`
}

func (d DeleteAimCatalogMcpServerRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteAimCatalogMcpServerRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteAimCatalogMcpServerRequest) GetOrganizationID() *string {
	if d == nil {
		return nil
	}
	return d.OrganizationID
}

func (d *DeleteAimCatalogMcpServerRequest) GetEnvironmentID() *string {
	if d == nil {
		return nil
	}
	return d.EnvironmentID
}

func (d *DeleteAimCatalogMcpServerRequest) GetHrid() string {
	if d == nil {
		return ""
	}
	return d.Hrid
}

type DeleteAimCatalogMcpServerResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Authentication is required
	AimHTTPError *shared.AimHTTPError
}

func (d *DeleteAimCatalogMcpServerResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteAimCatalogMcpServerResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteAimCatalogMcpServerResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteAimCatalogMcpServerResponse) GetAimHTTPError() *shared.AimHTTPError {
	if d == nil {
		return nil
	}
	return d.AimHTTPError
}
