// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0a472bbb782d

package operations

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/shared"
	"net/http"
)

type DeleteGroupGlobals struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
}

func (d DeleteGroupGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteGroupGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteGroupGlobals) GetOrganizationID() *string {
	if d == nil {
		return nil
	}
	return d.OrganizationID
}

func (d *DeleteGroupGlobals) GetEnvironmentID() *string {
	if d == nil {
		return nil
	}
	return d.EnvironmentID
}

type DeleteGroupRequest struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
	// Human-readable ID of a spec
	Hrid string `pathParam:"style=simple,explode=false,name=hrid"`
	// When true, the HRID path or spec value is treated as an existing UUID rather than
	// a human-readable identifier. This is to support backward compatibility for resources
	// created before migration to the automation API and should not be used for new resources.
	//
	HridContainsUUID *bool `default:"false" queryParam:"style=form,explode=true,name=hridContainsUUID"`
}

func (d DeleteGroupRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteGroupRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteGroupRequest) GetOrganizationID() *string {
	if d == nil {
		return nil
	}
	return d.OrganizationID
}

func (d *DeleteGroupRequest) GetEnvironmentID() *string {
	if d == nil {
		return nil
	}
	return d.EnvironmentID
}

func (d *DeleteGroupRequest) GetHrid() string {
	if d == nil {
		return ""
	}
	return d.Hrid
}

func (d *DeleteGroupRequest) GetHridContainsUUID() *bool {
	if d == nil {
		return nil
	}
	return d.HridContainsUUID
}

type DeleteGroupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthenticated
	HTTPError *shared.HTTPError
	// Default error
	Error *shared.Error
}

func (d *DeleteGroupResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteGroupResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteGroupResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteGroupResponse) GetHTTPError() *shared.HTTPError {
	if d == nil {
		return nil
	}
	return d.HTTPError
}

func (d *DeleteGroupResponse) GetError() *shared.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
