// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9a2d57e3fcd6

package operations

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/shared"
	"net/http"
)

type GetAimMcpProxyGlobals struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
}

func (g GetAimMcpProxyGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAimMcpProxyGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAimMcpProxyGlobals) GetOrganizationID() *string {
	if g == nil {
		return nil
	}
	return g.OrganizationID
}

func (g *GetAimMcpProxyGlobals) GetEnvironmentID() *string {
	if g == nil {
		return nil
	}
	return g.EnvironmentID
}

type GetAimMcpProxyRequest struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
	// Human-readable ID of a spec
	Hrid string `pathParam:"style=simple,explode=false,name=hrid"`
}

func (g GetAimMcpProxyRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAimMcpProxyRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAimMcpProxyRequest) GetOrganizationID() *string {
	if g == nil {
		return nil
	}
	return g.OrganizationID
}

func (g *GetAimMcpProxyRequest) GetEnvironmentID() *string {
	if g == nil {
		return nil
	}
	return g.EnvironmentID
}

func (g *GetAimMcpProxyRequest) GetHrid() string {
	if g == nil {
		return ""
	}
	return g.Hrid
}

type GetAimMcpProxyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// MCP proxy successfully retrieved
	AimMcpProxyState *shared.AimMcpProxyState
	// Authentication is required
	AimHTTPError *shared.AimHTTPError
}

func (g *GetAimMcpProxyResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetAimMcpProxyResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetAimMcpProxyResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetAimMcpProxyResponse) GetAimMcpProxyState() *shared.AimMcpProxyState {
	if g == nil {
		return nil
	}
	return g.AimMcpProxyState
}

func (g *GetAimMcpProxyResponse) GetAimHTTPError() *shared.AimHTTPError {
	if g == nil {
		return nil
	}
	return g.AimHTTPError
}
