// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/shared"
	"net/http"
)

type GetApplicationGlobals struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
}

func (g GetApplicationGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetApplicationGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetApplicationGlobals) GetOrganizationID() *string {
	if g == nil {
		return nil
	}
	return g.OrganizationID
}

func (g *GetApplicationGlobals) GetEnvironmentID() *string {
	if g == nil {
		return nil
	}
	return g.EnvironmentID
}

type GetApplicationRequest struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
	// Human-readable ID of a spec
	Hrid string `pathParam:"style=simple,explode=false,name=hrid"`
}

func (g GetApplicationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetApplicationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"hrid"}); err != nil {
		return err
	}
	return nil
}

func (g *GetApplicationRequest) GetOrganizationID() *string {
	if g == nil {
		return nil
	}
	return g.OrganizationID
}

func (g *GetApplicationRequest) GetEnvironmentID() *string {
	if g == nil {
		return nil
	}
	return g.EnvironmentID
}

func (g *GetApplicationRequest) GetHrid() string {
	if g == nil {
		return ""
	}
	return g.Hrid
}

type GetApplicationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Application successfully retrieved
	ApplicationState *shared.ApplicationState
	// Unauthenticated
	HTTPError *shared.HTTPError
	// Default error
	Error *shared.Error
}

func (g *GetApplicationResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetApplicationResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetApplicationResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetApplicationResponse) GetApplicationState() *shared.ApplicationState {
	if g == nil {
		return nil
	}
	return g.ApplicationState
}

func (g *GetApplicationResponse) GetHTTPError() *shared.HTTPError {
	if g == nil {
		return nil
	}
	return g.HTTPError
}

func (g *GetApplicationResponse) GetError() *shared.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
