// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-gravitee-apim/internal/sdk/internal/utils"
	"github.com/speakeasy/terraform-provider-gravitee-apim/internal/sdk/models/shared"
	"net/http"
)

type GetApplicationRequest struct {
	// Id of an organization.
	OrgID string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// Id of an environment.
	EnvID string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
	// Human-readable ID of a spec
	Hrid string `pathParam:"style=simple,explode=false,name=hrid"`
}

func (g GetApplicationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetApplicationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetApplicationRequest) GetOrgID() string {
	if o == nil {
		return ""
	}
	return o.OrgID
}

func (o *GetApplicationRequest) GetEnvID() string {
	if o == nil {
		return ""
	}
	return o.EnvID
}

func (o *GetApplicationRequest) GetHrid() string {
	if o == nil {
		return ""
	}
	return o.Hrid
}

type GetApplicationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful retrieval
	ApplicationState *shared.ApplicationState
	// Unauthenticated
	Error *shared.Error
}

func (o *GetApplicationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetApplicationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetApplicationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetApplicationResponse) GetApplicationState() *shared.ApplicationState {
	if o == nil {
		return nil
	}
	return o.ApplicationState
}

func (o *GetApplicationResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
