// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/shared"
	"net/http"
)

type GetAPISubscriptionGlobals struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
}

func (g GetAPISubscriptionGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAPISubscriptionGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAPISubscriptionGlobals) GetOrganizationID() *string {
	if g == nil {
		return nil
	}
	return g.OrganizationID
}

func (g *GetAPISubscriptionGlobals) GetEnvironmentID() *string {
	if g == nil {
		return nil
	}
	return g.EnvironmentID
}

type GetAPISubscriptionRequest struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
	// Human-readable ID of api
	APIHrid string `pathParam:"style=simple,explode=false,name=apiHrid"`
	// Human-readable ID of a spec
	Hrid string `pathParam:"style=simple,explode=false,name=hrid"`
}

func (g GetAPISubscriptionRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAPISubscriptionRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAPISubscriptionRequest) GetOrganizationID() *string {
	if g == nil {
		return nil
	}
	return g.OrganizationID
}

func (g *GetAPISubscriptionRequest) GetEnvironmentID() *string {
	if g == nil {
		return nil
	}
	return g.EnvironmentID
}

func (g *GetAPISubscriptionRequest) GetAPIHrid() string {
	if g == nil {
		return ""
	}
	return g.APIHrid
}

func (g *GetAPISubscriptionRequest) GetHrid() string {
	if g == nil {
		return ""
	}
	return g.Hrid
}

type GetAPISubscriptionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// API subscription successfully retrieved
	SubscriptionState *shared.SubscriptionState
	// Unauthenticated
	HTTPError *shared.HTTPError
	// Default error
	Error *shared.Error
}

func (g *GetAPISubscriptionResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetAPISubscriptionResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetAPISubscriptionResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetAPISubscriptionResponse) GetSubscriptionState() *shared.SubscriptionState {
	if g == nil {
		return nil
	}
	return g.SubscriptionState
}

func (g *GetAPISubscriptionResponse) GetHTTPError() *shared.HTTPError {
	if g == nil {
		return nil
	}
	return g.HTTPError
}

func (g *GetAPISubscriptionResponse) GetError() *shared.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
