// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d811dbb7c6e1

package operations

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/shared"
	"net/http"
)

type GetPortalDocumentationGlobals struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
}

func (g GetPortalDocumentationGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPortalDocumentationGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetPortalDocumentationGlobals) GetOrganizationID() *string {
	if g == nil {
		return nil
	}
	return g.OrganizationID
}

func (g *GetPortalDocumentationGlobals) GetEnvironmentID() *string {
	if g == nil {
		return nil
	}
	return g.EnvironmentID
}

type GetPortalDocumentationRequest struct {
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
	// Human-readable ID of a portal
	PortalHrid string `pathParam:"style=simple,explode=false,name=portalHrid"`
	// Human-readable ID of a spec
	Hrid string `pathParam:"style=simple,explode=false,name=hrid"`
}

func (g GetPortalDocumentationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPortalDocumentationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetPortalDocumentationRequest) GetOrganizationID() *string {
	if g == nil {
		return nil
	}
	return g.OrganizationID
}

func (g *GetPortalDocumentationRequest) GetEnvironmentID() *string {
	if g == nil {
		return nil
	}
	return g.EnvironmentID
}

func (g *GetPortalDocumentationRequest) GetPortalHrid() string {
	if g == nil {
		return ""
	}
	return g.PortalHrid
}

func (g *GetPortalDocumentationRequest) GetHrid() string {
	if g == nil {
		return ""
	}
	return g.Hrid
}

type GetPortalDocumentationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Documentation successfully retrieved
	DocumentationState *shared.DocumentationState
	// Unauthenticated
	HTTPError *shared.HTTPError
	// Default error
	Error *shared.Error
}

func (g *GetPortalDocumentationResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetPortalDocumentationResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetPortalDocumentationResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetPortalDocumentationResponse) GetDocumentationState() *shared.DocumentationState {
	if g == nil {
		return nil
	}
	return g.DocumentationState
}

func (g *GetPortalDocumentationResponse) GetHTTPError() *shared.HTTPError {
	if g == nil {
		return nil
	}
	return g.HTTPError
}

func (g *GetPortalDocumentationResponse) GetError() *shared.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
