// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: aea1040fbd32

package shared

// AimCatalogMcpResourceStatus - A resource the platform discovered on the upstream server; declared by the server, never by the author
type AimCatalogMcpResourceStatus struct {
	URI  *string `json:"uri,omitempty"`
	Name *string `json:"name,omitempty"`
	// Composed entity id of the resource, e.g. `mcp-resource.github.readme`
	EntityID *string `json:"entityId,omitempty"`
}

func (a *AimCatalogMcpResourceStatus) GetURI() *string {
	if a == nil {
		return nil
	}
	return a.URI
}

func (a *AimCatalogMcpResourceStatus) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AimCatalogMcpResourceStatus) GetEntityID() *string {
	if a == nil {
		return nil
	}
	return a.EntityID
}
