// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1261723b6cda

package shared

// AimCatalogMcpServerInfo - What the server said about itself when it was discovered
type AimCatalogMcpServerInfo struct {
	Name    *string `json:"name,omitempty"`
	Version *string `json:"version,omitempty"`
}

func (a *AimCatalogMcpServerInfo) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AimCatalogMcpServerInfo) GetVersion() *string {
	if a == nil {
		return nil
	}
	return a.Version
}
