// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 33a48cbbbeb3

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"time"
)

// AimCatalogMcpServerStateServerConnection - How the platform reaches the upstream MCP server
type AimCatalogMcpServerStateServerConnection struct {
	// URL of the upstream MCP server, http or https
	Endpoint string `json:"endpoint"`
	// MCP transport of the upstream server; `HTTP` is the streamable HTTP transport, the only one discovery supports today.
	Transport *AimCatalogMcpServerTransport `default:"HTTP" json:"transport"`
}

func (a AimCatalogMcpServerStateServerConnection) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AimCatalogMcpServerStateServerConnection) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AimCatalogMcpServerStateServerConnection) GetEndpoint() string {
	if a == nil {
		return ""
	}
	return a.Endpoint
}

func (a *AimCatalogMcpServerStateServerConnection) GetTransport() *AimCatalogMcpServerTransport {
	if a == nil {
		return nil
	}
	return a.Transport
}

// AimCatalogMcpServerState - State of a Catalog MCP server that has been created or updated.
type AimCatalogMcpServerState struct {
	// Resource UUID
	ID *string `json:"id,omitempty"`
	// The environment ID
	EnvironmentID *string `json:"environmentId,omitempty"`
	// The organization ID
	OrganizationID *string `json:"organizationId,omitempty"`
	// Findings about the applied spec
	Errors *AimErrors `json:"errors,omitempty"`
	// When the server's tools, prompts and resources were last synced; a registered server has synced at least once
	LastSyncedAt *time.Time `json:"lastSyncedAt,omitempty"`
	// What the server said about itself when it was discovered
	ServerInfo *AimCatalogMcpServerInfo `json:"serverInfo,omitempty"`
	// MCP protocol version negotiated with the server
	ProtocolVersion *string                       `json:"protocolVersion,omitempty"`
	Tools           []AimCatalogMcpToolStatus     `json:"tools,omitempty"`
	Prompts         []AimCatalogMcpPromptStatus   `json:"prompts,omitempty"`
	Resources       []AimCatalogMcpResourceStatus `json:"resources,omitempty"`
	// A unique human readable id identifying this resource
	Hrid string `json:"hrid"`
	// Stable catalog identity of the server, the name authorization policies reference: lowercase, dot-separated
	// segments, first segment `mcp-server`. Validated, never repaired: an invalid value, or a value already used by
	// another server of the environment, is rejected. Immutable once the server exists — declaring a different value
	// is rejected rather than applied, since nothing re-points the policies naming the old one. Delete the server and
	// declare it again to give it another identity.
	//
	EntityID string `json:"entityId"`
	// Human description shown in the Catalog
	Description      *string                                  `json:"description,omitempty"`
	ServerConnection AimCatalogMcpServerStateServerConnection `json:"connection"`
}

func (a AimCatalogMcpServerState) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AimCatalogMcpServerState) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AimCatalogMcpServerState) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AimCatalogMcpServerState) GetEnvironmentID() *string {
	if a == nil {
		return nil
	}
	return a.EnvironmentID
}

func (a *AimCatalogMcpServerState) GetOrganizationID() *string {
	if a == nil {
		return nil
	}
	return a.OrganizationID
}

func (a *AimCatalogMcpServerState) GetErrors() *AimErrors {
	if a == nil {
		return nil
	}
	return a.Errors
}

func (a *AimCatalogMcpServerState) GetLastSyncedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastSyncedAt
}

func (a *AimCatalogMcpServerState) GetServerInfo() *AimCatalogMcpServerInfo {
	if a == nil {
		return nil
	}
	return a.ServerInfo
}

func (a *AimCatalogMcpServerState) GetProtocolVersion() *string {
	if a == nil {
		return nil
	}
	return a.ProtocolVersion
}

func (a *AimCatalogMcpServerState) GetTools() []AimCatalogMcpToolStatus {
	if a == nil {
		return nil
	}
	return a.Tools
}

func (a *AimCatalogMcpServerState) GetPrompts() []AimCatalogMcpPromptStatus {
	if a == nil {
		return nil
	}
	return a.Prompts
}

func (a *AimCatalogMcpServerState) GetResources() []AimCatalogMcpResourceStatus {
	if a == nil {
		return nil
	}
	return a.Resources
}

func (a *AimCatalogMcpServerState) GetHrid() string {
	if a == nil {
		return ""
	}
	return a.Hrid
}

func (a *AimCatalogMcpServerState) GetEntityID() string {
	if a == nil {
		return ""
	}
	return a.EntityID
}

func (a *AimCatalogMcpServerState) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AimCatalogMcpServerState) GetServerConnection() AimCatalogMcpServerStateServerConnection {
	if a == nil {
		return AimCatalogMcpServerStateServerConnection{}
	}
	return a.ServerConnection
}
