// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: de77f7c28a23

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

// AimCatalogMcpServerSpecServerConnection - How the platform reaches the upstream MCP server
type AimCatalogMcpServerSpecServerConnection struct {
	// URL of the upstream MCP server, http or https
	Endpoint string `json:"endpoint"`
	// MCP transport of the upstream server; `HTTP` is the streamable HTTP transport, the only one discovery supports today.
	Transport *AimCatalogMcpServerTransport `default:"HTTP" json:"transport"`
	// Authentication the platform uses against the upstream MCP server, discriminated by `type`. Credential values are
	// stored verbatim: a literal, or a `secret://` URI pointing at a configured secret provider. They are never returned
	// by this API, and a spec that omits a credential clears the stored one.
	//
	Auth AimCatalogMcpServerAuth `json:"auth"`
}

func (a AimCatalogMcpServerSpecServerConnection) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AimCatalogMcpServerSpecServerConnection) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AimCatalogMcpServerSpecServerConnection) GetEndpoint() string {
	if a == nil {
		return ""
	}
	return a.Endpoint
}

func (a *AimCatalogMcpServerSpecServerConnection) GetTransport() *AimCatalogMcpServerTransport {
	if a == nil {
		return nil
	}
	return a.Transport
}

func (a *AimCatalogMcpServerSpecServerConnection) GetAuth() AimCatalogMcpServerAuth {
	if a == nil {
		return AimCatalogMcpServerAuth{}
	}
	return a.Auth
}

func (a *AimCatalogMcpServerSpecServerConnection) GetAuthNone() *AimCatalogMcpServerNoAuth {
	return a.GetAuth().AimCatalogMcpServerNoAuth
}

func (a *AimCatalogMcpServerSpecServerConnection) GetAuthHeader() *AimCatalogMcpServerHeaderAuth {
	return a.GetAuth().AimCatalogMcpServerHeaderAuth
}

func (a *AimCatalogMcpServerSpecServerConnection) GetAuthOauth2() *AimCatalogMcpServerOAuth2Auth {
	return a.GetAuth().AimCatalogMcpServerOAuth2Auth
}

// AimCatalogMcpServerSpec - Specification of an upstream MCP server registered in the AI Catalog. `entityId` is declared by the author and
// validated against the Gamma entity id grammar — it is never repaired or re-slugged. Tools, prompts and resources
// are discovered by the platform and reported in the state only.
type AimCatalogMcpServerSpec struct {
	// A unique human readable id identifying this resource
	Hrid string `json:"hrid"`
	// Stable catalog identity of the server, the name authorization policies reference: lowercase, dot-separated
	// segments, first segment `mcp-server`. Validated, never repaired: an invalid value, or a value already used by
	// another server of the environment, is rejected. Immutable once the server exists — declaring a different value
	// is rejected rather than applied, since nothing re-points the policies naming the old one. Delete the server and
	// declare it again to give it another identity.
	//
	EntityID string `json:"entityId"`
	// Human description shown in the Catalog
	Description      *string                                 `json:"description,omitempty"`
	ServerConnection AimCatalogMcpServerSpecServerConnection `json:"connection"`
}

func (a *AimCatalogMcpServerSpec) GetHrid() string {
	if a == nil {
		return ""
	}
	return a.Hrid
}

func (a *AimCatalogMcpServerSpec) GetEntityID() string {
	if a == nil {
		return ""
	}
	return a.EntityID
}

func (a *AimCatalogMcpServerSpec) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AimCatalogMcpServerSpec) GetServerConnection() AimCatalogMcpServerSpecServerConnection {
	if a == nil {
		return AimCatalogMcpServerSpecServerConnection{}
	}
	return a.ServerConnection
}
