// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0871dda72466

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

// AimMcpProxySpecProxy - What a `PROXY` fronts: one upstream MCP server and the credential the gateway presents to it. Required when
// `mode` is `PROXY`, rejected otherwise.
type AimMcpProxySpecProxy struct {
	// URL of the upstream MCP server, http or https; the gateway reaches it at runtime
	ServerURL string `json:"serverUrl"`
	// Authentication the gateway uses against the upstream MCP server, discriminated by `type`. Credential values
	// are stored verbatim: a literal, or a `secret://` URI pointing at a configured secret provider. They are
	// never returned by this API. Omitting `proxy.upstreamAuth`, or declaring `type: NONE`, means the gateway passes
	// the caller's credentials through — and clears any stored upstream authentication.
	//
	UpstreamAuth *AimMcpProxyUpstreamAuth `json:"upstreamAuth,omitempty"`
}

func (a *AimMcpProxySpecProxy) GetServerURL() string {
	if a == nil {
		return ""
	}
	return a.ServerURL
}

func (a *AimMcpProxySpecProxy) GetUpstreamAuth() *AimMcpProxyUpstreamAuth {
	if a == nil {
		return nil
	}
	return a.UpstreamAuth
}

func (a *AimMcpProxySpecProxy) GetUpstreamAuthNone() *AimMcpProxyNoUpstreamAuth {
	if v := a.GetUpstreamAuth(); v != nil {
		return v.AimMcpProxyNoUpstreamAuth
	}
	return nil
}

func (a *AimMcpProxySpecProxy) GetUpstreamAuthAPIKey() *AimMcpProxyAPIKeyUpstreamAuth {
	if v := a.GetUpstreamAuth(); v != nil {
		return v.AimMcpProxyAPIKeyUpstreamAuth
	}
	return nil
}

func (a *AimMcpProxySpecProxy) GetUpstreamAuthBearer() *AimMcpProxyBearerUpstreamAuth {
	if v := a.GetUpstreamAuth(); v != nil {
		return v.AimMcpProxyBearerUpstreamAuth
	}
	return nil
}

func (a *AimMcpProxySpecProxy) GetUpstreamAuthBasic() *AimMcpProxyBasicUpstreamAuth {
	if v := a.GetUpstreamAuth(); v != nil {
		return v.AimMcpProxyBasicUpstreamAuth
	}
	return nil
}

func (a *AimMcpProxySpecProxy) GetUpstreamAuthOauth2() *AimMcpProxyOAuth2UpstreamAuth {
	if v := a.GetUpstreamAuth(); v != nil {
		return v.AimMcpProxyOAuth2UpstreamAuth
	}
	return nil
}

// AimMcpProxySpecStudio - What a `STUDIO` exposes: tools picked from catalog MCP servers of the environment, the credential the
// gateway presents to each of those servers, and whether the platform's fine-grained authorization runs on
// tool calls. Tools converge as a set — adding, removing or re-aliasing one replaces the studio's tool
// surface — and `upstreamAuth` converges per server.
type AimMcpProxySpecStudio struct {
	// The tools the studio exposes, each named by the catalog server it comes from and its runtime name.
	// Every server named here needs an `upstreamAuth` entry. On a studio created with a `GRAVITEE_AM`
	// provider, a tool added after creation is served but not registered as a scope on the Access
	// Management domain; the apply reports it as a warning.
	//
	Tools []AimMcpProxyStudioToolInput `json:"tools"`
	// One entry per catalog server a tool comes from: the credential the gateway presents to that server,
	// stored verbatim and never returned, or `type: NONE` to say the server needs none. Nothing is inferred
	// from the credential the catalog synced the server with. An entry for a server no tool uses, a server
	// without an entry, or two entries for one server are rejected.
	//
	UpstreamAuth []AimMcpProxyStudioUpstreamAuth `json:"upstreamAuth"`
	// Inserts the platform's fine-grained authorization flow, which runs the `authz-pep` policy on
	// `tools/call` with the called tool as the resource; `false` removes it. That flow belongs to the
	// platform: `flows` may not carry an `authz-pep` step themselves, and the state reports the declared
	// flows without it.
	//
	EnableFGA *bool `default:"false" json:"enableFGA"`
}

func (a AimMcpProxySpecStudio) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AimMcpProxySpecStudio) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AimMcpProxySpecStudio) GetTools() []AimMcpProxyStudioToolInput {
	if a == nil {
		return []AimMcpProxyStudioToolInput{}
	}
	return a.Tools
}

func (a *AimMcpProxySpecStudio) GetUpstreamAuth() []AimMcpProxyStudioUpstreamAuth {
	if a == nil {
		return []AimMcpProxyStudioUpstreamAuth{}
	}
	return a.UpstreamAuth
}

func (a *AimMcpProxySpecStudio) GetEnableFGA() *bool {
	if a == nil {
		return nil
	}
	return a.EnableFGA
}

// AimMcpProxySpec - Specification of an MCP proxy. In `PROXY` mode the gateway exposes one upstream MCP server, declared under
// `proxy`, at `contextPath`; in `STUDIO` mode it exposes a curated set of tools picked from catalog MCP
// servers, declared under `studio`. Both sit behind the declared plans, which
// authenticate consumers against the declared identity providers, and run the declared policy flows on the
// traffic. `mode` and `entityId` are fixed at creation; `name`, `description`, `proxy`,
// `studio`, `contextPath`, the identity providers, the plan set, the flows and the lifecycle `state` converge
// on re-apply.
type AimMcpProxySpec struct {
	// A unique human readable id identifying this resource
	Hrid string `json:"hrid"`
	// Stable identity of the proxy, the name authorization policies reference: lowercase, dot-separated
	// segments, first segment `mcp-proxy`. Required. Validated,
	// never repaired: an invalid value, or a value already used by another MCP proxy of the environment, is
	// rejected. Immutable once the proxy exists — declaring a different value is rejected rather than
	// applied. Delete the proxy and declare it again to give it another identity. Uniqueness across the
	// environment is checked at apply time, not enforced by the store (AIAM-242): two concurrent applies
	// of the same entityId can both pass.
	//
	EntityID string `json:"entityId"`
	// Display name of the proxy; converges on re-apply
	Name string `json:"name"`
	// Human description of the proxy; converges on re-apply
	Description *string `json:"description,omitempty"`
	// Context path the gateway serves the proxy on; must be available in the environment
	ContextPath string `json:"contextPath"`
	// Shape of the proxy, and the one block it carries: `PROXY` fronts one upstream MCP server, declared under
	// `proxy`; `STUDIO` composes a curated tool surface out of catalog MCP servers, declared under `studio`. The
	// other mode's block is rejected. Required. Fixed at creation: declaring another mode on
	// an existing proxy is rejected, and changing it is a delete and a new declaration.
	//
	Mode   AimMcpProxyMode        `json:"mode"`
	Proxy  *AimMcpProxySpecProxy  `json:"proxy,omitempty"`
	Studio *AimMcpProxySpecStudio `json:"studio,omitempty"`
	// Lifecycle of the proxy on the gateway. `STARTED` runs it with the last applied definition and redeploys it
	// after every apply that changes it; `STOPPED` makes the gateway answer 404 and stores changes without
	// deploying them, which the next `STARTED` does. `STARTED` when omitted. Reported back as the lifecycle APIM
	// observes. A start or a deploy the gateway side refuses fails the apply with a `500` carrying the technical
	// code `gamma.mcp.lifecycle.failed` and the operation, the proxy and the cause as parameters; the declaration
	// is stored, and the next apply starts the proxy or redeploys the one APIM reports out of sync.
	//
	State *AimMcpProxyLifecycleState `default:"STARTED" json:"state"`
	// How the gateway selects among the proxy's flows. `DEFAULT` runs every flow whose selectors match;
	// `BEST_MATCH` runs the one whose selectors match best. Omitted, APIM's defaults apply and the state
	// reports no execution block.
	//
	FlowExecution *AimMcpProxyFlowExecution `json:"flowExecution,omitempty"`
	// Policy flows of the proxy, in execution order, run after the flows of the plan the request matched.
	// The manifest owns them: on every apply the proxy's flows are replaced by the declared ones, so a
	// flow authored in the policy studio survives only if the manifest carries it, and omitting `flows`
	// removes them all. Each step's configuration is validated against its policy's schema, on apply and
	// on dry run, and reported back as stored.
	//
	Flows []AimMcpProxyFlow `json:"flows,omitempty"`
	// Authorization servers declared on the proxy as OAuth2 resources, which OAUTH2 plans reference through
	// `provider`. Converged by name: a declared provider the proxy lacks is attached; a declared provider
	// whose configuration differs from the proxy's resource is rejected, except a generic provider's
	// `clientSecret`, which replaces the stored one when it differs and is kept when omitted; a resource
	// no longer declared is left in place; a declared provider named like a resource the proxy holds
	// disabled, or under another type, is rejected. At most one `GRAVITEE_AM` provider, provisioned when
	// the proxy is created only.
	//
	IdentityProviders []AimMcpProxyIdentityProvider `json:"identityProviders,omitempty"`
	// Plans consumers subscribe to, converged by name: a declared plan the proxy does not have is created
	// and published, a plan the proxy holds in staging is published, a plan the declaration no longer
	// carries is closed — closing terminates its subscriptions — and a plan cannot be changed in place
	// under the same name. At least one plan is required.
	//
	Plans []AimMcpProxyPlan `json:"plans"`
}

func (a AimMcpProxySpec) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AimMcpProxySpec) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AimMcpProxySpec) GetHrid() string {
	if a == nil {
		return ""
	}
	return a.Hrid
}

func (a *AimMcpProxySpec) GetEntityID() string {
	if a == nil {
		return ""
	}
	return a.EntityID
}

func (a *AimMcpProxySpec) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AimMcpProxySpec) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AimMcpProxySpec) GetContextPath() string {
	if a == nil {
		return ""
	}
	return a.ContextPath
}

func (a *AimMcpProxySpec) GetMode() AimMcpProxyMode {
	if a == nil {
		return AimMcpProxyMode("")
	}
	return a.Mode
}

func (a *AimMcpProxySpec) GetProxy() *AimMcpProxySpecProxy {
	if a == nil {
		return nil
	}
	return a.Proxy
}

func (a *AimMcpProxySpec) GetStudio() *AimMcpProxySpecStudio {
	if a == nil {
		return nil
	}
	return a.Studio
}

func (a *AimMcpProxySpec) GetState() *AimMcpProxyLifecycleState {
	if a == nil {
		return nil
	}
	return a.State
}

func (a *AimMcpProxySpec) GetFlowExecution() *AimMcpProxyFlowExecution {
	if a == nil {
		return nil
	}
	return a.FlowExecution
}

func (a *AimMcpProxySpec) GetFlows() []AimMcpProxyFlow {
	if a == nil {
		return nil
	}
	return a.Flows
}

func (a *AimMcpProxySpec) GetIdentityProviders() []AimMcpProxyIdentityProvider {
	if a == nil {
		return nil
	}
	return a.IdentityProviders
}

func (a *AimMcpProxySpec) GetPlans() []AimMcpProxyPlan {
	if a == nil {
		return []AimMcpProxyPlan{}
	}
	return a.Plans
}
