// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 82ce441e1ce5

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

// TypeOauth2Auth0 - Kind of authorization server
type TypeOauth2Auth0 string

const (
	TypeOauth2Auth0Oauth2Auth0 TypeOauth2Auth0 = "OAUTH2_AUTH0"
)

func (e TypeOauth2Auth0) ToPointer() *TypeOauth2Auth0 {
	return &e
}
func (e *TypeOauth2Auth0) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OAUTH2_AUTH0":
		*e = TypeOauth2Auth0(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypeOauth2Auth0: %v", v)
	}
}

type Oauth2Generic struct {
	// Auth0 tenant domain
	Domain string `json:"domain"`
	// Audience of the tokens the gateway accepts
	Audience string `json:"audience"`
	// Name of the provider, the resource name on the proxy and the value plans reference
	Name string `json:"name"`
	// Kind of authorization server
	Type *TypeOauth2Auth0 `default:"OAUTH2_AUTH0" json:"type"`
}

func (o Oauth2Generic) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *Oauth2Generic) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *Oauth2Generic) GetDomain() string {
	if o == nil {
		return ""
	}
	return o.Domain
}

func (o *Oauth2Generic) GetAudience() string {
	if o == nil {
		return ""
	}
	return o.Audience
}

func (o *Oauth2Generic) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Oauth2Generic) GetType() *TypeOauth2Auth0 {
	if o == nil {
		return nil
	}
	return o.Type
}

// #region class-body-oauth2generic
// #endregion class-body-oauth2generic

// IntrospectionEndpointMethod - HTTP method of the introspection call
type IntrospectionEndpointMethod string

const (
	IntrospectionEndpointMethodGet  IntrospectionEndpointMethod = "GET"
	IntrospectionEndpointMethodPost IntrospectionEndpointMethod = "POST"
)

func (e IntrospectionEndpointMethod) ToPointer() *IntrospectionEndpointMethod {
	return &e
}
func (e *IntrospectionEndpointMethod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "GET":
		fallthrough
	case "POST":
		*e = IntrospectionEndpointMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntrospectionEndpointMethod: %v", v)
	}
}

// TypeOauth2Generic - Kind of authorization server
type TypeOauth2Generic string

const (
	TypeOauth2GenericOauth2Generic TypeOauth2Generic = "OAUTH2_GENERIC"
)

func (e TypeOauth2Generic) ToPointer() *TypeOauth2Generic {
	return &e
}
func (e *TypeOauth2Generic) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OAUTH2_GENERIC":
		*e = TypeOauth2Generic(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypeOauth2Generic: %v", v)
	}
}

type GraviteeAmOutput struct {
	// Issuer URL of the authorization server, the base the endpoints are resolved against
	IssuerURL string `json:"issuerUrl"`
	// Token introspection endpoint, as a path relative to `issuerUrl` or as an absolute URL beneath it;
	// stored and reported as the path
	//
	IntrospectionEndpoint string `json:"introspectionEndpoint"`
	// HTTP method of the introspection call
	IntrospectionEndpointMethod IntrospectionEndpointMethod `json:"introspectionEndpointMethod"`
	// Client id the gateway introspects tokens with
	ClientID *string `json:"clientId,omitempty"`
	// UserInfo endpoint, same rule as `introspectionEndpoint`
	UserInfoEndpoint *string `json:"userInfoEndpoint,omitempty"`
	// Name of the provider, the resource name on the proxy and the value plans reference
	Name string `json:"name"`
	// Kind of authorization server
	Type *TypeOauth2Generic `default:"OAUTH2_GENERIC" json:"type"`
}

func (g GraviteeAmOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GraviteeAmOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GraviteeAmOutput) GetIssuerURL() string {
	if g == nil {
		return ""
	}
	return g.IssuerURL
}

func (g *GraviteeAmOutput) GetIntrospectionEndpoint() string {
	if g == nil {
		return ""
	}
	return g.IntrospectionEndpoint
}

func (g *GraviteeAmOutput) GetIntrospectionEndpointMethod() IntrospectionEndpointMethod {
	if g == nil {
		return IntrospectionEndpointMethod("")
	}
	return g.IntrospectionEndpointMethod
}

func (g *GraviteeAmOutput) GetClientID() *string {
	if g == nil {
		return nil
	}
	return g.ClientID
}

func (g *GraviteeAmOutput) GetUserInfoEndpoint() *string {
	if g == nil {
		return nil
	}
	return g.UserInfoEndpoint
}

func (g *GraviteeAmOutput) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GraviteeAmOutput) GetType() *TypeOauth2Generic {
	if g == nil {
		return nil
	}
	return g.Type
}

// TypeGraviteeAm - Kind of authorization server
type TypeGraviteeAm string

const (
	TypeGraviteeAmGraviteeAm TypeGraviteeAm = "GRAVITEE_AM"
)

func (e TypeGraviteeAm) ToPointer() *TypeGraviteeAm {
	return &e
}
func (e *TypeGraviteeAm) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "GRAVITEE_AM":
		*e = TypeGraviteeAm(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypeGraviteeAm: %v", v)
	}
}

type AimMcpProxyIdentityProviderTrue struct {
	// Name of the provider, the resource name on the proxy and the value plans reference
	Name string `json:"name"`
	// Kind of authorization server
	Type *TypeGraviteeAm `default:"GRAVITEE_AM" json:"type"`
}

func (a AimMcpProxyIdentityProviderTrue) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AimMcpProxyIdentityProviderTrue) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AimMcpProxyIdentityProviderTrue) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AimMcpProxyIdentityProviderTrue) GetType() *TypeGraviteeAm {
	if a == nil {
		return nil
	}
	return a.Type
}

type AimMcpProxyIdentityProviderOutputType string

const (
	AimMcpProxyIdentityProviderOutputTypeGraviteeAm    AimMcpProxyIdentityProviderOutputType = "GRAVITEE_AM"
	AimMcpProxyIdentityProviderOutputTypeOauth2Generic AimMcpProxyIdentityProviderOutputType = "OAUTH2_GENERIC"
	AimMcpProxyIdentityProviderOutputTypeOauth2Auth0   AimMcpProxyIdentityProviderOutputType = "OAUTH2_AUTH0"
)

// AimMcpProxyIdentityProviderOutput - An authorization server declared on the proxy, discriminated by `type`. Each becomes an OAuth2 resource of
// the proxy's API, named after `name`, which OAUTH2 plans reference through `provider`.
type AimMcpProxyIdentityProviderOutput struct {
	AimMcpProxyIdentityProviderTrue *AimMcpProxyIdentityProviderTrue `queryParam:"inline" union:"member"`
	GraviteeAmOutput                *GraviteeAmOutput                `queryParam:"inline" union:"member"`
	Oauth2Generic                   *Oauth2Generic                   `queryParam:"inline" union:"member"`

	Type AimMcpProxyIdentityProviderOutputType
}

func CreateAimMcpProxyIdentityProviderOutputGraviteeAm(graviteeAm AimMcpProxyIdentityProviderTrue) AimMcpProxyIdentityProviderOutput {
	typ := AimMcpProxyIdentityProviderOutputTypeGraviteeAm

	typStr := TypeGraviteeAm(typ)
	graviteeAm.Type = &typStr

	return AimMcpProxyIdentityProviderOutput{
		AimMcpProxyIdentityProviderTrue: &graviteeAm,
		Type:                            typ,
	}
}

func CreateAimMcpProxyIdentityProviderOutputOauth2Generic(oauth2Generic GraviteeAmOutput) AimMcpProxyIdentityProviderOutput {
	typ := AimMcpProxyIdentityProviderOutputTypeOauth2Generic

	typStr := TypeOauth2Generic(typ)
	oauth2Generic.Type = &typStr

	return AimMcpProxyIdentityProviderOutput{
		GraviteeAmOutput: &oauth2Generic,
		Type:             typ,
	}
}

func CreateAimMcpProxyIdentityProviderOutputOauth2Auth0(oauth2Auth0 Oauth2Generic) AimMcpProxyIdentityProviderOutput {
	typ := AimMcpProxyIdentityProviderOutputTypeOauth2Auth0

	typStr := TypeOauth2Auth0(typ)
	oauth2Auth0.Type = &typStr

	return AimMcpProxyIdentityProviderOutput{
		Oauth2Generic: &oauth2Auth0,
		Type:          typ,
	}
}

func (u *AimMcpProxyIdentityProviderOutput) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "GRAVITEE_AM":
		aimMcpProxyIdentityProviderTrue := new(AimMcpProxyIdentityProviderTrue)
		if err := utils.UnmarshalJSON(data, &aimMcpProxyIdentityProviderTrue, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == GRAVITEE_AM) type AimMcpProxyIdentityProviderTrue within AimMcpProxyIdentityProviderOutput: %w", string(data), err)
		}

		u.AimMcpProxyIdentityProviderTrue = aimMcpProxyIdentityProviderTrue
		u.Type = AimMcpProxyIdentityProviderOutputTypeGraviteeAm
		return nil
	case "OAUTH2_GENERIC":
		graviteeAmOutput := new(GraviteeAmOutput)
		if err := utils.UnmarshalJSON(data, &graviteeAmOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == OAUTH2_GENERIC) type GraviteeAmOutput within AimMcpProxyIdentityProviderOutput: %w", string(data), err)
		}

		u.GraviteeAmOutput = graviteeAmOutput
		u.Type = AimMcpProxyIdentityProviderOutputTypeOauth2Generic
		return nil
	case "OAUTH2_AUTH0":
		oauth2Generic := new(Oauth2Generic)
		if err := utils.UnmarshalJSON(data, &oauth2Generic, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == OAUTH2_AUTH0) type Oauth2Generic within AimMcpProxyIdentityProviderOutput: %w", string(data), err)
		}

		u.Oauth2Generic = oauth2Generic
		u.Type = AimMcpProxyIdentityProviderOutputTypeOauth2Auth0
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for AimMcpProxyIdentityProviderOutput", string(data))
}

func (u AimMcpProxyIdentityProviderOutput) MarshalJSON() ([]byte, error) {
	if u.AimMcpProxyIdentityProviderTrue != nil {
		return utils.MarshalJSON(u.AimMcpProxyIdentityProviderTrue, "", true)
	}

	if u.GraviteeAmOutput != nil {
		return utils.MarshalJSON(u.GraviteeAmOutput, "", true)
	}

	if u.Oauth2Generic != nil {
		return utils.MarshalJSON(u.Oauth2Generic, "", true)
	}

	return nil, errors.New("could not marshal union type AimMcpProxyIdentityProviderOutput: all fields are null")
}

type GraviteeAm struct {
	// Issuer URL of the authorization server, the base the endpoints are resolved against
	IssuerURL string `json:"issuerUrl"`
	// Token introspection endpoint, as a path relative to `issuerUrl` or as an absolute URL beneath it;
	// stored and reported as the path
	//
	IntrospectionEndpoint string `json:"introspectionEndpoint"`
	// HTTP method of the introspection call
	IntrospectionEndpointMethod IntrospectionEndpointMethod `json:"introspectionEndpointMethod"`
	// Client id the gateway introspects tokens with
	ClientID *string `json:"clientId,omitempty"`
	// Client secret the gateway introspects tokens with, a literal or a `secret://` URI stored verbatim and
	// never returned. Omitted on a later apply, the stored secret is kept; a different value replaces the
	// proxy's resource in place and redeploys the proxy, which is how a rotated reference reaches the gateway.
	//
	ClientSecret *string `json:"clientSecret,omitempty"`
	// UserInfo endpoint, same rule as `introspectionEndpoint`
	UserInfoEndpoint *string `json:"userInfoEndpoint,omitempty"`
	// Name of the provider, the resource name on the proxy and the value plans reference
	Name string `json:"name"`
	// Kind of authorization server
	Type *TypeOauth2Generic `default:"OAUTH2_GENERIC" json:"type"`
}

func (g GraviteeAm) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GraviteeAm) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GraviteeAm) GetIssuerURL() string {
	if g == nil {
		return ""
	}
	return g.IssuerURL
}

func (g *GraviteeAm) GetIntrospectionEndpoint() string {
	if g == nil {
		return ""
	}
	return g.IntrospectionEndpoint
}

func (g *GraviteeAm) GetIntrospectionEndpointMethod() IntrospectionEndpointMethod {
	if g == nil {
		return IntrospectionEndpointMethod("")
	}
	return g.IntrospectionEndpointMethod
}

func (g *GraviteeAm) GetClientID() *string {
	if g == nil {
		return nil
	}
	return g.ClientID
}

func (g *GraviteeAm) GetClientSecret() *string {
	if g == nil {
		return nil
	}
	return g.ClientSecret
}

func (g *GraviteeAm) GetUserInfoEndpoint() *string {
	if g == nil {
		return nil
	}
	return g.UserInfoEndpoint
}

func (g *GraviteeAm) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GraviteeAm) GetType() *TypeOauth2Generic {
	if g == nil {
		return nil
	}
	return g.Type
}

type AimMcpProxyIdentityProviderType string

const (
	AimMcpProxyIdentityProviderTypeGraviteeAm    AimMcpProxyIdentityProviderType = "GRAVITEE_AM"
	AimMcpProxyIdentityProviderTypeOauth2Generic AimMcpProxyIdentityProviderType = "OAUTH2_GENERIC"
	AimMcpProxyIdentityProviderTypeOauth2Auth0   AimMcpProxyIdentityProviderType = "OAUTH2_AUTH0"
)

// AimMcpProxyIdentityProvider - An authorization server declared on the proxy, discriminated by `type`. Each becomes an OAuth2 resource of
// the proxy's API, named after `name`, which OAUTH2 plans reference through `provider`.
type AimMcpProxyIdentityProvider struct {
	AimMcpProxyIdentityProviderTrue *AimMcpProxyIdentityProviderTrue `queryParam:"inline" union:"member"`
	GraviteeAm                      *GraviteeAm                      `queryParam:"inline" union:"member"`
	Oauth2Generic                   *Oauth2Generic                   `queryParam:"inline" union:"member"`

	Type AimMcpProxyIdentityProviderType
}

func CreateAimMcpProxyIdentityProviderGraviteeAm(graviteeAm AimMcpProxyIdentityProviderTrue) AimMcpProxyIdentityProvider {
	typ := AimMcpProxyIdentityProviderTypeGraviteeAm

	typStr := TypeGraviteeAm(typ)
	graviteeAm.Type = &typStr

	return AimMcpProxyIdentityProvider{
		AimMcpProxyIdentityProviderTrue: &graviteeAm,
		Type:                            typ,
	}
}

func CreateAimMcpProxyIdentityProviderOauth2Generic(oauth2Generic GraviteeAm) AimMcpProxyIdentityProvider {
	typ := AimMcpProxyIdentityProviderTypeOauth2Generic

	typStr := TypeOauth2Generic(typ)
	oauth2Generic.Type = &typStr

	return AimMcpProxyIdentityProvider{
		GraviteeAm: &oauth2Generic,
		Type:       typ,
	}
}

func CreateAimMcpProxyIdentityProviderOauth2Auth0(oauth2Auth0 Oauth2Generic) AimMcpProxyIdentityProvider {
	typ := AimMcpProxyIdentityProviderTypeOauth2Auth0

	typStr := TypeOauth2Auth0(typ)
	oauth2Auth0.Type = &typStr

	return AimMcpProxyIdentityProvider{
		Oauth2Generic: &oauth2Auth0,
		Type:          typ,
	}
}

func (u *AimMcpProxyIdentityProvider) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "GRAVITEE_AM":
		aimMcpProxyIdentityProviderTrue := new(AimMcpProxyIdentityProviderTrue)
		if err := utils.UnmarshalJSON(data, &aimMcpProxyIdentityProviderTrue, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == GRAVITEE_AM) type AimMcpProxyIdentityProviderTrue within AimMcpProxyIdentityProvider: %w", string(data), err)
		}

		u.AimMcpProxyIdentityProviderTrue = aimMcpProxyIdentityProviderTrue
		u.Type = AimMcpProxyIdentityProviderTypeGraviteeAm
		return nil
	case "OAUTH2_GENERIC":
		graviteeAm := new(GraviteeAm)
		if err := utils.UnmarshalJSON(data, &graviteeAm, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == OAUTH2_GENERIC) type GraviteeAm within AimMcpProxyIdentityProvider: %w", string(data), err)
		}

		u.GraviteeAm = graviteeAm
		u.Type = AimMcpProxyIdentityProviderTypeOauth2Generic
		return nil
	case "OAUTH2_AUTH0":
		oauth2Generic := new(Oauth2Generic)
		if err := utils.UnmarshalJSON(data, &oauth2Generic, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == OAUTH2_AUTH0) type Oauth2Generic within AimMcpProxyIdentityProvider: %w", string(data), err)
		}

		u.Oauth2Generic = oauth2Generic
		u.Type = AimMcpProxyIdentityProviderTypeOauth2Auth0
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for AimMcpProxyIdentityProvider", string(data))
}

func (u AimMcpProxyIdentityProvider) MarshalJSON() ([]byte, error) {
	if u.AimMcpProxyIdentityProviderTrue != nil {
		return utils.MarshalJSON(u.AimMcpProxyIdentityProviderTrue, "", true)
	}

	if u.GraviteeAm != nil {
		return utils.MarshalJSON(u.GraviteeAm, "", true)
	}

	if u.Oauth2Generic != nil {
		return utils.MarshalJSON(u.Oauth2Generic, "", true)
	}

	return nil, errors.New("could not marshal union type AimMcpProxyIdentityProvider: all fields are null")
}
