// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 693fd75e3e96

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

// Mode - Flow selection mode
type Mode string

const (
	ModeDefault   Mode = "DEFAULT"
	ModeBestMatch Mode = "BEST_MATCH"
)

func (e Mode) ToPointer() *Mode {
	return &e
}
func (e *Mode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DEFAULT":
		fallthrough
	case "BEST_MATCH":
		*e = Mode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Mode: %v", v)
	}
}

// AimMcpProxyFlowExecution - How the gateway selects among the proxy's flows. `DEFAULT` runs every flow whose selectors match;
// `BEST_MATCH` runs the one whose selectors match best. Omitted, APIM's defaults apply and the state
// reports no execution block.
type AimMcpProxyFlowExecution struct {
	// Flow selection mode
	Mode *Mode `default:"DEFAULT" json:"mode"`
	// Reject a request no flow matches; false when omitted
	MatchRequired *bool `default:"false" json:"matchRequired"`
}

func (a AimMcpProxyFlowExecution) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AimMcpProxyFlowExecution) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AimMcpProxyFlowExecution) GetMode() *Mode {
	if a == nil {
		return nil
	}
	return a.Mode
}

func (a *AimMcpProxyFlowExecution) GetMatchRequired() *bool {
	if a == nil {
		return nil
	}
	return a.MatchRequired
}
