// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

type Analytics struct {
	// Whether or not analytics is enabled.
	Enabled  *bool      `default:"true" json:"enabled"`
	Sampling *Sampling  `json:"sampling,omitempty"`
	Logging  *LoggingV4 `json:"logging,omitempty"`
	Tracing  *TracingV4 `json:"tracing,omitempty"`
}

func (a Analytics) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *Analytics) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *Analytics) GetEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.Enabled
}

func (a *Analytics) GetSampling() *Sampling {
	if a == nil {
		return nil
	}
	return a.Sampling
}

func (a *Analytics) GetLogging() *LoggingV4 {
	if a == nil {
		return nil
	}
	return a.Logging
}

func (a *Analytics) GetTracing() *TracingV4 {
	if a == nil {
		return nil
	}
	return a.Tracing
}
