// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 05af8b419800

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"time"
)

// APIKeySpec - API key specification with optional expiry date
type APIKeySpec struct {
	// The custom API key value.
	Key string `json:"key"`
	// Optional expiry date for this API key.
	ExpireAt *time.Time `json:"expireAt,omitempty"`
}

func (a APIKeySpec) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIKeySpec) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIKeySpec) GetKey() string {
	if a == nil {
		return ""
	}
	return a.Key
}

func (a *APIKeySpec) GetExpireAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.ExpireAt
}
