// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

// APIV4StateAnalytics - API analytics configuration to enable/disable what can be observed.
type APIV4StateAnalytics struct {
	// Whether or not analytics are enabled.
	Enabled *bool `json:"enabled,omitempty"`
	// API analytics sampling (message API only). This is meant to log only a portion to avoid overflowing the log sink.
	Sampling *Sampling `json:"sampling,omitempty"`
	// API logging configuration (Not for native APIs)
	Logging *LoggingV4 `json:"logging,omitempty"`
	// OpenTelemetry tracing (Not for native APIs)
	Tracing *TracingV4 `json:"tracing,omitempty"`
}

func (a *APIV4StateAnalytics) GetEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.Enabled
}

func (a *APIV4StateAnalytics) GetSampling() *Sampling {
	if a == nil {
		return nil
	}
	return a.Sampling
}

func (a *APIV4StateAnalytics) GetLogging() *LoggingV4 {
	if a == nil {
		return nil
	}
	return a.Logging
}

func (a *APIV4StateAnalytics) GetTracing() *TracingV4 {
	if a == nil {
		return nil
	}
	return a.Tracing
}

// APIV4StateFailover - Defines the failover behavior to bypass endpoints when some are slow.
type APIV4StateFailover struct {
	// Automatically redirects request to the next endpoint if the response is too slow.
	Enabled *bool `default:"false" json:"enabled"`
	// Limit the number of retry attempts before recording an error. Each attempt dynamically selects an endpoint based on the load balancing algorithm.
	MaxRetries *int `default:"2" json:"maxRetries"`
	// Define a threshold for slow responses. Requests exceeding this duration are recorded as slow.
	SlowCallDuration *int64 `default:"2000" json:"slowCallDuration"`
	// The duration in milliseconds to indicate how long the circuit breaker should stay open, before it switches to half open.
	OpenStateDuration *int64 `default:"10000" json:"openStateDuration"`
	// The maximum number of failures allowed before the circuit breaker can calculate the error rate.
	MaxFailures *int `default:"5" json:"maxFailures"`
	// If true, a circuit breaker breaker will be dedicated for each subscriber, else, one and only circuit breaker will be used for the API.
	PerSubscription *bool `default:"true" json:"perSubscription"`
}

func (a APIV4StateFailover) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIV4StateFailover) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIV4StateFailover) GetEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.Enabled
}

func (a *APIV4StateFailover) GetMaxRetries() *int {
	if a == nil {
		return nil
	}
	return a.MaxRetries
}

func (a *APIV4StateFailover) GetSlowCallDuration() *int64 {
	if a == nil {
		return nil
	}
	return a.SlowCallDuration
}

func (a *APIV4StateFailover) GetOpenStateDuration() *int64 {
	if a == nil {
		return nil
	}
	return a.OpenStateDuration
}

func (a *APIV4StateFailover) GetMaxFailures() *int {
	if a == nil {
		return nil
	}
	return a.MaxFailures
}

func (a *APIV4StateFailover) GetPerSubscription() *bool {
	if a == nil {
		return nil
	}
	return a.PerSubscription
}

// APIV4StateFlowExecution - Flow execution enablement (Not applicable for Native API)
type APIV4StateFlowExecution struct {
	// DEFAULT : all flows that match the conditions are executed in the order they are defined BEST_MATCH: only the best matching flow will be executed
	Mode *FlowMode `default:"DEFAULT" json:"mode"`
	// To indicate failure if no flow matches the request.
	MatchRequired *bool `default:"false" json:"matchRequired"`
}

func (a APIV4StateFlowExecution) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIV4StateFlowExecution) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIV4StateFlowExecution) GetMode() *FlowMode {
	if a == nil {
		return nil
	}
	return a.Mode
}

func (a *APIV4StateFlowExecution) GetMatchRequired() *bool {
	if a == nil {
		return nil
	}
	return a.MatchRequired
}

// APIV4State - API state
type APIV4State struct {
	// A unique human readable id identifying this resource
	Hrid string `json:"hrid"`
	// API's name. Duplicate names can exists.
	Name string `json:"name"`
	// API's version. It's a simple string only used to help manage API versioning.
	Version string `json:"version"`
	// API's type.
	Type APIType `json:"type"`
	// Basic API documentation to describe what this API does.
	Description *string `json:"description,omitempty"`
	// Sharding tags that restrict deployment to Gateways having those tags on. No tags means "always deploy".
	Tags []string `json:"tags,omitempty"`
	// The list of listeners defining how this API can be called. They depend on the API type.
	Listeners []Listener `json:"listeners"`
	// Common endpoints properties and container of endpoints specifying backends this API can call.
	EndpointGroups []EndpointGroupV4    `json:"endpointGroups"`
	Analytics      *APIV4StateAnalytics `json:"analytics,omitempty"`
	Failover       *APIV4StateFailover  `json:"failover,omitempty"`
	// Properties usable using EL.
	Properties []PropertyOutput `json:"properties,omitempty"`
	// Data resources usable in policy to access (mostly) external data (authentication, cache, registries...).
	Resources []APIResource `json:"resources,omitempty"`
	// Available plans for the API to define API security. You must provide a plan if `state` is `STARTED`. Plans are prioritized by their position in the list, with earlier entries having higher priority.
	Plans         []PlanV4                 `json:"plans,omitempty"`
	FlowExecution *APIV4StateFlowExecution `json:"flowExecution,omitempty"`
	// Common flows for the API where traffic policies are configured.
	Flows []FlowV4 `json:"flows,omitempty"`
	// Map of content-type dependent Response Templates for the API (Not applicable for Native
	// API) to customize Gateway responses body on predefined errors.
	//
	// Key of the map is the error code.
	//
	ResponseTemplates map[string]map[string]ResponseTemplate `json:"responseTemplates,omitempty"`
	// Api services (dynamic properties)
	Services *APIServices `json:"services,omitempty"`
	// Name or UUIDs of existing groups (of users) associated with this API.
	Groups []string `json:"groups,omitempty"`
	// The visibility of the entity regarding the portal.
	Visibility *Visibility `default:"PUBLIC" json:"visibility"`
	// STARTED will make this API callable on tis context path, STOPPED will yield 404 error
	State *LifecycleState `json:"state,omitempty"`
	// User owner of this. Can perform all possible actions on it.
	PrimaryOwner *PrimaryOwner `json:"primaryOwner,omitempty"`
	// Informative labels for this API.
	Labels []string `json:"labels,omitempty"`
	// The list of API's metadata.
	Metadata []Metadata `json:"metadata,omitempty"`
	// The status of the API regarding the console.
	LifecycleState APILifecycleState `json:"lifecycleState"`
	// The list of category names (or UUID) associated with this API.
	Categories []string `json:"categories,omitempty"`
	// Users that can access or manage the API (depending on their roles).
	Members []Member `json:"members,omitempty"`
	// Pages for the API. Elements positioned earlier in the list are displayed first, with subsequent elements appearing below.
	Pages []PageV4 `json:"pages,omitempty"`
	// When a resource has been created regardless of errors, this field is used to persist the error message encountered during validation
	Errors *Errors `json:"errors,omitempty"`
	// API's uuid.
	ID *string `json:"id,omitempty"`
	// When promoting an API from one environment to the other, this ID identifies the API across those different environments.
	CrossID *string `json:"crossId,omitempty"`
	// The environment ID of the API.
	EnvironmentID *string `json:"environmentId,omitempty"`
	// The organization ID of the API.
	OrganizationID *string `json:"organizationId,omitempty"`
}

func (a APIV4State) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIV4State) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIV4State) GetHrid() string {
	if a == nil {
		return ""
	}
	return a.Hrid
}

func (a *APIV4State) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *APIV4State) GetVersion() string {
	if a == nil {
		return ""
	}
	return a.Version
}

func (a *APIV4State) GetType() APIType {
	if a == nil {
		return APIType("")
	}
	return a.Type
}

func (a *APIV4State) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *APIV4State) GetTags() []string {
	if a == nil {
		return nil
	}
	return a.Tags
}

func (a *APIV4State) GetListeners() []Listener {
	if a == nil {
		return []Listener{}
	}
	return a.Listeners
}

func (a *APIV4State) GetEndpointGroups() []EndpointGroupV4 {
	if a == nil {
		return []EndpointGroupV4{}
	}
	return a.EndpointGroups
}

func (a *APIV4State) GetAnalytics() *APIV4StateAnalytics {
	if a == nil {
		return nil
	}
	return a.Analytics
}

func (a *APIV4State) GetFailover() *APIV4StateFailover {
	if a == nil {
		return nil
	}
	return a.Failover
}

func (a *APIV4State) GetProperties() []PropertyOutput {
	if a == nil {
		return nil
	}
	return a.Properties
}

func (a *APIV4State) GetResources() []APIResource {
	if a == nil {
		return nil
	}
	return a.Resources
}

func (a *APIV4State) GetPlans() []PlanV4 {
	if a == nil {
		return nil
	}
	return a.Plans
}

func (a *APIV4State) GetFlowExecution() *APIV4StateFlowExecution {
	if a == nil {
		return nil
	}
	return a.FlowExecution
}

func (a *APIV4State) GetFlows() []FlowV4 {
	if a == nil {
		return nil
	}
	return a.Flows
}

func (a *APIV4State) GetResponseTemplates() map[string]map[string]ResponseTemplate {
	if a == nil {
		return nil
	}
	return a.ResponseTemplates
}

func (a *APIV4State) GetServices() *APIServices {
	if a == nil {
		return nil
	}
	return a.Services
}

func (a *APIV4State) GetGroups() []string {
	if a == nil {
		return nil
	}
	return a.Groups
}

func (a *APIV4State) GetVisibility() *Visibility {
	if a == nil {
		return nil
	}
	return a.Visibility
}

func (a *APIV4State) GetState() *LifecycleState {
	if a == nil {
		return nil
	}
	return a.State
}

func (a *APIV4State) GetPrimaryOwner() *PrimaryOwner {
	if a == nil {
		return nil
	}
	return a.PrimaryOwner
}

func (a *APIV4State) GetLabels() []string {
	if a == nil {
		return nil
	}
	return a.Labels
}

func (a *APIV4State) GetMetadata() []Metadata {
	if a == nil {
		return nil
	}
	return a.Metadata
}

func (a *APIV4State) GetLifecycleState() APILifecycleState {
	if a == nil {
		return APILifecycleState("")
	}
	return a.LifecycleState
}

func (a *APIV4State) GetCategories() []string {
	if a == nil {
		return nil
	}
	return a.Categories
}

func (a *APIV4State) GetMembers() []Member {
	if a == nil {
		return nil
	}
	return a.Members
}

func (a *APIV4State) GetPages() []PageV4 {
	if a == nil {
		return nil
	}
	return a.Pages
}

func (a *APIV4State) GetErrors() *Errors {
	if a == nil {
		return nil
	}
	return a.Errors
}

func (a *APIV4State) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *APIV4State) GetCrossID() *string {
	if a == nil {
		return nil
	}
	return a.CrossID
}

func (a *APIV4State) GetEnvironmentID() *string {
	if a == nil {
		return nil
	}
	return a.EnvironmentID
}

func (a *APIV4State) GetOrganizationID() *string {
	if a == nil {
		return nil
	}
	return a.OrganizationID
}
