// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ApplicationState - Application state that has been created/updated
type ApplicationState struct {
	// A unique human readable id identifying this resource
	Hrid string `json:"hrid"`
	// Application's name. Duplicate names can exists.
	Name string `json:"name"`
	// Application's description.
	Description string `json:"description"`
	// Application's domain.
	Domain *string `json:"domain,omitempty"`
	// List of groups associated with the Application.
	// This groups are id or name references to existing groups in APIM.
	Groups []string `json:"groups,omitempty"`
	// Application's picture Url.
	PictureURL *string `json:"pictureUrl,omitempty"`
	// Application's background.
	Background *string `json:"background,omitempty"`
	// Primary owner
	PrimaryOwner *PrimaryOwner `json:"primaryOwner,omitempty"`
	// Application settings
	Settings *ApplicationSettings `json:"settings,omitempty"`
	// The list of Application's metadata.
	Metadata []Metadata `json:"metadata,omitempty"`
	// Set of members associated with the application
	Members []Member `json:"members,omitempty"`
	// When a resource has been created regardless of errors, this field is used to persist the error message encountered during admission
	Errors *Errors `json:"errors,omitempty"`
	// Application's uuid.
	ID *string `json:"id,omitempty"`
}

func (o *ApplicationState) GetHrid() string {
	if o == nil {
		return ""
	}
	return o.Hrid
}

func (o *ApplicationState) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ApplicationState) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *ApplicationState) GetDomain() *string {
	if o == nil {
		return nil
	}
	return o.Domain
}

func (o *ApplicationState) GetGroups() []string {
	if o == nil {
		return nil
	}
	return o.Groups
}

func (o *ApplicationState) GetPictureURL() *string {
	if o == nil {
		return nil
	}
	return o.PictureURL
}

func (o *ApplicationState) GetBackground() *string {
	if o == nil {
		return nil
	}
	return o.Background
}

func (o *ApplicationState) GetPrimaryOwner() *PrimaryOwner {
	if o == nil {
		return nil
	}
	return o.PrimaryOwner
}

func (o *ApplicationState) GetSettings() *ApplicationSettings {
	if o == nil {
		return nil
	}
	return o.Settings
}

func (o *ApplicationState) GetMetadata() []Metadata {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *ApplicationState) GetMembers() []Member {
	if o == nil {
		return nil
	}
	return o.Members
}

func (o *ApplicationState) GetErrors() *Errors {
	if o == nil {
		return nil
	}
	return o.Errors
}

func (o *ApplicationState) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}
