// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ApplicationTLSSettings - Application TLS settings
type ApplicationTLSSettings struct {
	// Application TLS client certificate
	ClientCertificate string `json:"clientCertificate"`
}

func (a *ApplicationTLSSettings) GetClientCertificate() string {
	if a == nil {
		return ""
	}
	return a.ClientCertificate
}
