// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ApplicationOAuthClientSettings - Application OAuth client settings
type ApplicationOAuthClientSettings struct {
	// OAuth client grant types
	GrantTypes []string `json:"grantTypes,omitempty"`
	// OAuth client redirect Uris
	RedirectUris []string `json:"redirectUris,omitempty"`
	// OAuth client application type
	ApplicationType *string `json:"applicationType,omitempty"`
}

func (o *ApplicationOAuthClientSettings) GetGrantTypes() []string {
	if o == nil {
		return nil
	}
	return o.GrantTypes
}

func (o *ApplicationOAuthClientSettings) GetRedirectUris() []string {
	if o == nil {
		return nil
	}
	return o.RedirectUris
}

func (o *ApplicationOAuthClientSettings) GetApplicationType() *string {
	if o == nil {
		return nil
	}
	return o.ApplicationType
}
