// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a8e8d2701d5b

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"time"
)

// ClientCertificate - A client certificate for mTLS authentication
type ClientCertificate struct {
	// Certificate name for identification
	Name string `json:"name"`
	// Certificate in PEM format
	Content string `json:"content"`
	// Date when this certificate becomes active
	StartsAt *time.Time `json:"startsAt,omitempty"`
	// Date when this certificate will be removed
	EndsAt *time.Time `json:"endsAt,omitempty"`
}

func (c ClientCertificate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientCertificate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientCertificate) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *ClientCertificate) GetContent() string {
	if c == nil {
		return ""
	}
	return c.Content
}

func (c *ClientCertificate) GetStartsAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.StartsAt
}

func (c *ClientCertificate) GetEndsAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndsAt
}
