// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5e6f38a0f60b

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

type DictionaryProviderType string

const (
	DictionaryProviderTypeHTTP DictionaryProviderType = "HTTP"
)

// DictionaryProvider - Provider of a 'DYNAMIC' type dictionary
type DictionaryProvider struct {
	HTTPDictionaryProvider *HTTPDictionaryProvider `queryParam:"inline" union:"member"`

	Type DictionaryProviderType
}

func CreateDictionaryProviderHTTP(http HTTPDictionaryProvider) DictionaryProvider {
	typ := DictionaryProviderTypeHTTP

	typStr := HTTPDictionaryProviderType(typ)
	http.Type = typStr

	return DictionaryProvider{
		HTTPDictionaryProvider: &http,
		Type:                   typ,
	}
}

func (u *DictionaryProvider) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "HTTP":
		httpDictionaryProvider := new(HTTPDictionaryProvider)
		if err := utils.UnmarshalJSON(data, &httpDictionaryProvider, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == HTTP) type HTTPDictionaryProvider within DictionaryProvider: %w", string(data), err)
		}

		u.HTTPDictionaryProvider = httpDictionaryProvider
		u.Type = DictionaryProviderTypeHTTP
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for DictionaryProvider", string(data))
}

func (u DictionaryProvider) MarshalJSON() ([]byte, error) {
	if u.HTTPDictionaryProvider != nil {
		return utils.MarshalJSON(u.HTTPDictionaryProvider, "", true)
	}

	return nil, errors.New("could not marshal union type DictionaryProvider: all fields are null")
}
