// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6deb03255492

package shared

// DictionaryState - Dictionary state
type DictionaryState struct {
	// A unique human readable id identifying this resource
	Hrid string `json:"hrid"`
	// Display name of the dictionary
	Name string `json:"name"`
	// If true, a `MANUAL` type dictionary is deployed in the gateway, a `DYNAMIC` type dictionary is started.
	// Changing this value back to false will stop the dictionary or undeploy it.
	//
	Deployed bool `json:"deployed"`
	// Detailed description of the dictionary
	Description *string `json:"description,omitempty"`
	// Type of dictionary. MANUAL is to be updated manually, DYNAMIC is updated and deployed automatically.
	Type DictionaryType `json:"type"`
	// A manual dictionary with static key/value properties.
	Manual *ManualDictionarySpec `json:"manual,omitempty"`
	// A dynamic dictionary populated from an external provider on a schedule.
	Dynamic *DynamicDictionarySpec `json:"dynamic,omitempty"`
	// Resource UUID.
	ID *string `json:"id,omitempty"`
	// The environment ID.
	EnvironmentID *string `json:"environmentId,omitempty"`
	// The organization ID.
	OrganizationID *string `json:"organizationId,omitempty"`
	// When a resource has been created regardless of errors, this field is used to persist the error message encountered during validation
	Errors *Errors `json:"errors,omitempty"`
}

func (d *DictionaryState) GetHrid() string {
	if d == nil {
		return ""
	}
	return d.Hrid
}

func (d *DictionaryState) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DictionaryState) GetDeployed() bool {
	if d == nil {
		return false
	}
	return d.Deployed
}

func (d *DictionaryState) GetDescription() *string {
	if d == nil {
		return nil
	}
	return d.Description
}

func (d *DictionaryState) GetType() DictionaryType {
	if d == nil {
		return DictionaryType("")
	}
	return d.Type
}

func (d *DictionaryState) GetManual() *ManualDictionarySpec {
	if d == nil {
		return nil
	}
	return d.Manual
}

func (d *DictionaryState) GetDynamic() *DynamicDictionarySpec {
	if d == nil {
		return nil
	}
	return d.Dynamic
}

func (d *DictionaryState) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *DictionaryState) GetEnvironmentID() *string {
	if d == nil {
		return nil
	}
	return d.EnvironmentID
}

func (d *DictionaryState) GetOrganizationID() *string {
	if d == nil {
		return nil
	}
	return d.OrganizationID
}

func (d *DictionaryState) GetErrors() *Errors {
	if d == nil {
		return nil
	}
	return d.Errors
}
