// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Dlq struct {
	// The endpoint of the DLQ.
	Endpoint *string `json:"endpoint,omitempty"`
}

func (o *Dlq) GetEndpoint() *string {
	if o == nil {
		return nil
	}
	return o.Endpoint
}
