// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: cbde6af66854

package shared

// DocumentState - A simple mock document for testing purposes.
type DocumentState struct {
	// Human-readable ID of the document
	Hrid string `json:"hrid"`
	// Name of the document
	Name string `json:"name"`
	// Content of the document
	Content *string `json:"content,omitempty"`
	// API's uuid.
	ID *string `json:"id,omitempty"`
	// The environment ID of the API.
	EnvironmentID *string `json:"environmentId,omitempty"`
	// The organization ID of the API.
	OrganizationID *string `json:"organizationId,omitempty"`
}

func (d *DocumentState) GetHrid() string {
	if d == nil {
		return ""
	}
	return d.Hrid
}

func (d *DocumentState) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DocumentState) GetContent() *string {
	if d == nil {
		return nil
	}
	return d.Content
}

func (d *DocumentState) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *DocumentState) GetEnvironmentID() *string {
	if d == nil {
		return nil
	}
	return d.EnvironmentID
}

func (d *DocumentState) GetOrganizationID() *string {
	if d == nil {
		return nil
	}
	return d.OrganizationID
}
