// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// EncryptedProperty - API property can be used within the API using EL expression `{#api.properties['key']}.
type EncryptedProperty struct {
	// Property key.
	Key string `json:"key"`
	// Property value to be encrypted.
	Value string `json:"value"`
}

func (e *EncryptedProperty) GetKey() string {
	if e == nil {
		return ""
	}
	return e.Key
}

func (e *EncryptedProperty) GetValue() string {
	if e == nil {
		return ""
	}
	return e.Value
}
