// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4f09e3f5a8bb

package shared

// EndpointGroupServices - API Endpoint Group Services
type EndpointGroupServices struct {
	// Specifies an API property fetch using an external source.
	Discovery *ServiceV4 `json:"discovery,omitempty"`
	// Specifies an API property fetch using an external source.
	HealthCheck *ServiceV4 `json:"healthCheck,omitempty"`
}

func (e *EndpointGroupServices) GetDiscovery() *ServiceV4 {
	if e == nil {
		return nil
	}
	return e.Discovery
}

func (e *EndpointGroupServices) GetHealthCheck() *ServiceV4 {
	if e == nil {
		return nil
	}
	return e.HealthCheck
}
