// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// EndpointGroupServices - API Endpoint Group Services
type EndpointGroupServices struct {
	// Service
	Discovery *ServiceV4 `json:"discovery,omitempty"`
	// Service
	HealthCheck *ServiceV4 `json:"healthCheck,omitempty"`
}

func (e *EndpointGroupServices) GetDiscovery() *ServiceV4 {
	if e == nil {
		return nil
	}
	return e.Discovery
}

func (e *EndpointGroupServices) GetHealthCheck() *ServiceV4 {
	if e == nil {
		return nil
	}
	return e.HealthCheck
}
