// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

// Entrypoint - API Endpoint
type Entrypoint struct {
	// The type of the entrypoint
	Type string `json:"type"`
	// Type of the quality of service.
	Qos *Qos `default:"AUTO" json:"qos"`
	// DLQ
	Dlq           *Dlq `json:"dlq,omitempty"`
	Configuration any  `json:"configuration,omitempty"`
}

func (e Entrypoint) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Entrypoint) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (e *Entrypoint) GetType() string {
	if e == nil {
		return ""
	}
	return e.Type
}

func (e *Entrypoint) GetQos() *Qos {
	if e == nil {
		return nil
	}
	return e.Qos
}

func (e *Entrypoint) GetDlq() *Dlq {
	if e == nil {
		return nil
	}
	return e.Dlq
}

func (e *Entrypoint) GetConfiguration() any {
	if e == nil {
		return nil
	}
	return e.Configuration
}
