// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a388f67481aa

package shared

// InvalidValueResponse - The invalid value.
type InvalidValueResponse struct {
}

type DetailResponse struct {
	// The error message
	Message *string `json:"message,omitempty"`
	// The json path of the field in error.
	Location *string `json:"location,omitempty"`
	// The invalid value.
	InvalidValue *InvalidValueResponse `json:"invalidValue,omitempty"`
}

func (d *DetailResponse) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}

func (d *DetailResponse) GetLocation() *string {
	if d == nil {
		return nil
	}
	return d.Location
}

func (d *DetailResponse) GetInvalidValue() *InvalidValueResponse {
	if d == nil {
		return nil
	}
	return d.InvalidValue
}

// Error
type Error struct {
	// Error code
	HTTPStatus *int `json:"httpStatus,omitempty"`
	// Error message
	Message *string `json:"message,omitempty"`
	// A technical code to identify the error
	TechnicalCode *string `json:"technicalCode,omitempty"`
	// A map of parameters to be used in the error message
	Parameters map[string]string `json:"parameters,omitempty"`
	// A list of details about the error
	Details []DetailResponse `json:"details,omitempty"`
}

func (e *Error) GetHTTPStatus() *int {
	if e == nil {
		return nil
	}
	return e.HTTPStatus
}

func (e *Error) GetMessage() *string {
	if e == nil {
		return nil
	}
	return e.Message
}

func (e *Error) GetTechnicalCode() *string {
	if e == nil {
		return nil
	}
	return e.TechnicalCode
}

func (e *Error) GetParameters() map[string]string {
	if e == nil {
		return nil
	}
	return e.Parameters
}

func (e *Error) GetDetails() []DetailResponse {
	if e == nil {
		return nil
	}
	return e.Details
}
