// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

type FlowV4 struct {
	// Flow's uuid.
	ID *string `json:"id,omitempty"`
	// Flow's name.
	Name *string `json:"name,omitempty"`
	// Is the flow enabled.
	Enabled   *bool      `default:"true" json:"enabled"`
	Selectors []Selector `json:"selectors,omitempty"`
	// Flow step used for PROXY and MESSAGE APIs
	Request []StepV4 `json:"request,omitempty"`
	// Flow step used for PROXY and MESSAGE APIs
	Response []StepV4 `json:"response,omitempty"`
	// Flow step used for MESSAGE and NATIVE APIs
	Subscribe []StepV4 `json:"subscribe,omitempty"`
	// Flow step used for MESSAGE and NATIVE APIs
	Publish []StepV4 `json:"publish,omitempty"`
	// Flow step used for NATIVE APIs
	Connect []StepV4 `json:"connect,omitempty"`
	// Flow step used for NATIVE APIs
	Interact []StepV4 `json:"interact,omitempty"`
	// Flow's tags.
	Tags []string `json:"tags,omitempty"`
}

func (f FlowV4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FlowV4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FlowV4) GetID() *string {
	if f == nil {
		return nil
	}
	return f.ID
}

func (f *FlowV4) GetName() *string {
	if f == nil {
		return nil
	}
	return f.Name
}

func (f *FlowV4) GetEnabled() *bool {
	if f == nil {
		return nil
	}
	return f.Enabled
}

func (f *FlowV4) GetSelectors() []Selector {
	if f == nil {
		return nil
	}
	return f.Selectors
}

func (f *FlowV4) GetRequest() []StepV4 {
	if f == nil {
		return nil
	}
	return f.Request
}

func (f *FlowV4) GetResponse() []StepV4 {
	if f == nil {
		return nil
	}
	return f.Response
}

func (f *FlowV4) GetSubscribe() []StepV4 {
	if f == nil {
		return nil
	}
	return f.Subscribe
}

func (f *FlowV4) GetPublish() []StepV4 {
	if f == nil {
		return nil
	}
	return f.Publish
}

func (f *FlowV4) GetConnect() []StepV4 {
	if f == nil {
		return nil
	}
	return f.Connect
}

func (f *FlowV4) GetInteract() []StepV4 {
	if f == nil {
		return nil
	}
	return f.Interact
}

func (f *FlowV4) GetTags() []string {
	if f == nil {
		return nil
	}
	return f.Tags
}
