// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

type FlowStep struct {
	// FlowStep condition
	Condition *string `json:"condition,omitempty"`
	// FlowStep configuration is a map of arbitrary key-values
	Configuration *string `json:"configuration,omitempty"`
	// FlowStep description
	Description *string `json:"description,omitempty"`
	// Indicate if this FlowStep is enabled or not
	Enabled *bool `default:"true" json:"enabled"`
	// The message condition (supports EL expressions)
	MessageCondition *string `json:"messageCondition,omitempty"`
	// FlowStep name
	Name *string `json:"name,omitempty"`
	// FlowStep policy
	Policy *string `json:"policy,omitempty"`
}

func (f FlowStep) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FlowStep) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FlowStep) GetCondition() *string {
	if f == nil {
		return nil
	}
	return f.Condition
}

func (f *FlowStep) GetConfiguration() *string {
	if f == nil {
		return nil
	}
	return f.Configuration
}

func (f *FlowStep) GetDescription() *string {
	if f == nil {
		return nil
	}
	return f.Description
}

func (f *FlowStep) GetEnabled() *bool {
	if f == nil {
		return nil
	}
	return f.Enabled
}

func (f *FlowStep) GetMessageCondition() *string {
	if f == nil {
		return nil
	}
	return f.MessageCondition
}

func (f *FlowStep) GetName() *string {
	if f == nil {
		return nil
	}
	return f.Name
}

func (f *FlowStep) GetPolicy() *string {
	if f == nil {
		return nil
	}
	return f.Policy
}
