// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c9928c613d32

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

// GroupState - Group state combining spec and status after creation/update.
type GroupState struct {
	// Resource UUID.
	ID *string `json:"id,omitempty"`
	// The environment ID.
	EnvironmentID *string `json:"environmentId,omitempty"`
	// The organization ID.
	OrganizationID *string `json:"organizationId,omitempty"`
	// When a resource has been created regardless of errors, this field is used to persist the error message encountered during validation
	Errors *Errors `json:"errors,omitempty"`
	// Number of members in the group.
	MemberCount *int64 `json:"memberCount,omitempty"`
	// A unique human readable id identifying this resource
	Hrid string `json:"hrid"`
	// Group's name.
	Name string `json:"name"`
	// Members of this group with their IDP source and role assignments.
	// Members that do not already exist in the IDP will be ignored.
	//
	Members []GroupMember `json:"members,omitempty"`
	// Default role, per scope, given to a member who joins the group, including members
	// mapped from an identity provider.
	// Keys are `API`, `APPLICATION` and `API_PRODUCT`; any other key is refused with a 400.
	// When omitted or empty, the group's default roles on the platform are left untouched.
	// When it declares at least one scope, the map is the whole set: a scope absent from it
	// loses its default role.
	// `PRIMARY_OWNER` is refused; an unknown role name is reported as a warning and that scope
	// is left without a default role.
	//
	DefaultMemberRoles map[string]string `json:"defaultMemberRoles,omitempty"`
	// If true, members will be notified when the group is synced with APIM.
	NotifyMembers *bool `default:"true" json:"notifyMembers"`
}

func (g GroupState) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GroupState) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GroupState) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *GroupState) GetEnvironmentID() *string {
	if g == nil {
		return nil
	}
	return g.EnvironmentID
}

func (g *GroupState) GetOrganizationID() *string {
	if g == nil {
		return nil
	}
	return g.OrganizationID
}

func (g *GroupState) GetErrors() *Errors {
	if g == nil {
		return nil
	}
	return g.Errors
}

func (g *GroupState) GetMemberCount() *int64 {
	if g == nil {
		return nil
	}
	return g.MemberCount
}

func (g *GroupState) GetHrid() string {
	if g == nil {
		return ""
	}
	return g.Hrid
}

func (g *GroupState) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GroupState) GetMembers() []GroupMember {
	if g == nil {
		return nil
	}
	return g.Members
}

func (g *GroupState) GetDefaultMemberRoles() map[string]string {
	if g == nil {
		return nil
	}
	return g.DefaultMemberRoles
}

func (g *GroupState) GetNotifyMembers() *bool {
	if g == nil {
		return nil
	}
	return g.NotifyMembers
}
