// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type HTTPListener struct {
	// Listener type.
	Type         ListenerType `json:"type"`
	Entrypoints  []Entrypoint `json:"entrypoints,omitempty"`
	Servers      []string     `json:"servers,omitempty"`
	Paths        []PathV4     `json:"paths,omitempty"`
	PathMappings []string     `json:"pathMappings,omitempty"`
	Cors         *Cors        `json:"cors,omitempty"`
}

func (o *HTTPListener) GetType() ListenerType {
	if o == nil {
		return ListenerType("")
	}
	return o.Type
}

func (o *HTTPListener) GetEntrypoints() []Entrypoint {
	if o == nil {
		return nil
	}
	return o.Entrypoints
}

func (o *HTTPListener) GetServers() []string {
	if o == nil {
		return nil
	}
	return o.Servers
}

func (o *HTTPListener) GetPaths() []PathV4 {
	if o == nil {
		return nil
	}
	return o.Paths
}

func (o *HTTPListener) GetPathMappings() []string {
	if o == nil {
		return nil
	}
	return o.PathMappings
}

func (o *HTTPListener) GetCors() *Cors {
	if o == nil {
		return nil
	}
	return o.Cors
}
