// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ca73dcb94bff

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

// KafkaListener - Kafka listener
type KafkaListener struct {
	// Listener type.
	Type ListenerType `json:"type"`
	// A list of possible entrypoint of the same type.
	Entrypoints []Entrypoint `json:"entrypoints,omitempty"`
	// Restrict the API to a given "server id", when the gateway runs in multiple servers mode (several ports per protocol).
	Servers []string `json:"servers,omitempty"`
	// A hostname for which the API will match against SNI.
	Host string `json:"host"`
}

func (k KafkaListener) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(k, "", false)
}

func (k *KafkaListener) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &k, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (k *KafkaListener) GetType() ListenerType {
	if k == nil {
		return ListenerType("")
	}
	return k.Type
}

func (k *KafkaListener) GetEntrypoints() []Entrypoint {
	if k == nil {
		return nil
	}
	return k.Entrypoints
}

func (k *KafkaListener) GetServers() []string {
	if k == nil {
		return nil
	}
	return k.Servers
}

func (k *KafkaListener) GetHost() string {
	if k == nil {
		return ""
	}
	return k.Host
}
