// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// KafkaListener - Kafka listener
type KafkaListener struct {
	// Listener type.
	Type        ListenerType `json:"type"`
	Entrypoints []Entrypoint `json:"entrypoints,omitempty"`
	Servers     []string     `json:"servers,omitempty"`
	// A hostname for which the API will match against SNI.
	Host string `json:"host"`
	// The port of the listener
	Port *int64 `json:"port,omitempty"`
}

func (o *KafkaListener) GetType() ListenerType {
	if o == nil {
		return ListenerType("")
	}
	return o.Type
}

func (o *KafkaListener) GetEntrypoints() []Entrypoint {
	if o == nil {
		return nil
	}
	return o.Entrypoints
}

func (o *KafkaListener) GetServers() []string {
	if o == nil {
		return nil
	}
	return o.Servers
}

func (o *KafkaListener) GetHost() string {
	if o == nil {
		return ""
	}
	return o.Host
}

func (o *KafkaListener) GetPort() *int64 {
	if o == nil {
		return nil
	}
	return o.Port
}
