// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// LoggingV4 - API logging configuration
type LoggingV4 struct {
	Condition        *string `json:"condition,omitempty"`
	MessageCondition *string `json:"messageCondition,omitempty"`
	// API logging content
	Content *LoggingContentV4 `json:"content,omitempty"`
	// Logging phase
	Phase *LoggingPhase `json:"phase,omitempty"`
	// API logging mode
	Mode *LoggingModeV4 `json:"mode,omitempty"`
}

func (l *LoggingV4) GetCondition() *string {
	if l == nil {
		return nil
	}
	return l.Condition
}

func (l *LoggingV4) GetMessageCondition() *string {
	if l == nil {
		return nil
	}
	return l.MessageCondition
}

func (l *LoggingV4) GetContent() *LoggingContentV4 {
	if l == nil {
		return nil
	}
	return l.Content
}

func (l *LoggingV4) GetPhase() *LoggingPhase {
	if l == nil {
		return nil
	}
	return l.Phase
}

func (l *LoggingV4) GetMode() *LoggingModeV4 {
	if l == nil {
		return nil
	}
	return l.Mode
}
