// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type LoggingModeV4 struct {
	Endpoint   *bool `json:"endpoint,omitempty"`
	Entrypoint *bool `json:"entrypoint,omitempty"`
}

func (o *LoggingModeV4) GetEndpoint() *bool {
	if o == nil {
		return nil
	}
	return o.Endpoint
}

func (o *LoggingModeV4) GetEntrypoint() *bool {
	if o == nil {
		return nil
	}
	return o.Entrypoint
}
