// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// LoggingModeV4 - API logging mode
type LoggingModeV4 struct {
	Endpoint   *bool `json:"endpoint,omitempty"`
	Entrypoint *bool `json:"entrypoint,omitempty"`
}

func (l *LoggingModeV4) GetEndpoint() *bool {
	if l == nil {
		return nil
	}
	return l.Endpoint
}

func (l *LoggingModeV4) GetEntrypoint() *bool {
	if l == nil {
		return nil
	}
	return l.Entrypoint
}
