// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// Metadata is a generic data structure used internally
type Metadata struct {
	// The key of the metadata if different from sanitized name (lowercase + hyphens).
	Key *string `json:"key,omitempty"`
	// The name of the metadata.
	Name string `json:"name"`
	// The format of the metadata.
	Format MetadataFormat `json:"format"`
	// The value of the metadata.
	Value *string `json:"value,omitempty"`
	// The default value of the metadata if the value is not set.
	DefaultValue *string `json:"defaultValue,omitempty"`
	// if this metadata should be hidden
	Hidden *bool `json:"hidden,omitempty"`
}

func (m *Metadata) GetKey() *string {
	if m == nil {
		return nil
	}
	return m.Key
}

func (m *Metadata) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *Metadata) GetFormat() MetadataFormat {
	if m == nil {
		return MetadataFormat("")
	}
	return m.Format
}

func (m *Metadata) GetValue() *string {
	if m == nil {
		return nil
	}
	return m.Value
}

func (m *Metadata) GetDefaultValue() *string {
	if m == nil {
		return nil
	}
	return m.DefaultValue
}

func (m *Metadata) GetHidden() *bool {
	if m == nil {
		return nil
	}
	return m.Hidden
}
