// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Metadata struct {
	// The key of the metadata.
	Key *string `json:"key,omitempty"`
	// The name of the metadata.
	Name *string `json:"name,omitempty"`
	// The format of the metadata.
	Format *MetadataFormat `json:"format,omitempty"`
	// The value of the metadata.
	Value *string `json:"value,omitempty"`
	// The default value of the metadata.
	DefaultValue *string `json:"defaultValue,omitempty"`
}

func (m *Metadata) GetKey() *string {
	if m == nil {
		return nil
	}
	return m.Key
}

func (m *Metadata) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *Metadata) GetFormat() *MetadataFormat {
	if m == nil {
		return nil
	}
	return m.Format
}

func (m *Metadata) GetValue() *string {
	if m == nil {
		return nil
	}
	return m.Value
}

func (m *Metadata) GetDefaultValue() *string {
	if m == nil {
		return nil
	}
	return m.DefaultValue
}
