// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"time"
)

// PageV4Input - Documentation page. Can be of multiple formats.
type PageV4Input struct {
	// A unique human readable id identifying this resource
	Hrid string `json:"hrid"`
	// This is the display name of the page in APIM and on the portal.
	// This field can be edited safely if you want to rename a page.
	//
	Name string `json:"name"`
	// The type of the documentation page or folder.
	Type PageType `json:"type"`
	// The content of the page, if any.
	Content *string `json:"content,omitempty"`
	// The order used to display the page in APIM and on the portal.
	Order int64 `json:"order"`
	// If true, the page will be accessible from the portal (default is false)
	Published *bool `default:"false" json:"published"`
	// The visibility of the resource regarding the portal.
	Visibility *Visibility `default:"PUBLIC" json:"visibility"`
	// Page's last update date.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Page's content type.
	ContentType *string `json:"contentType,omitempty"`
	// Allow you to fetch pages from various external sources,
	// overriding page content each time the source is fetched.
	//
	Source *PageSource `json:"source,omitempty"`
	// Key/value page configuration (Configure swagger UI or or use Redoc instead)
	Configuration map[string]string `json:"configuration,omitempty"`
	// If true, this page will be displayed as the homepage of your API documentation.
	Homepage *bool `json:"homepage,omitempty"`
	// If your page contains a folder, setting this field to the map key associated to the
	// folder entry will be reflected into APIM by making the page a child of this folder.
	//
	Parent *string `json:"parent,omitempty"`
	// List of access controls.
	AccessControls []AccessControl `json:"accessControls,omitempty"`
	// Page's metadata.
	Metadata map[string]string `json:"metadata,omitempty"`
	// If folder is published but not shown in Portal.
	Hidden *bool `json:"hidden,omitempty"`
	// List of page translations.
	Translations []PageV4TranslationInput `json:"translations,omitempty"`
}

func (p PageV4Input) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PageV4Input) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"hrid", "name", "type", "order"}); err != nil {
		return err
	}
	return nil
}

func (p *PageV4Input) GetHrid() string {
	if p == nil {
		return ""
	}
	return p.Hrid
}

func (p *PageV4Input) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PageV4Input) GetType() PageType {
	if p == nil {
		return PageType("")
	}
	return p.Type
}

func (p *PageV4Input) GetContent() *string {
	if p == nil {
		return nil
	}
	return p.Content
}

func (p *PageV4Input) GetOrder() int64 {
	if p == nil {
		return 0
	}
	return p.Order
}

func (p *PageV4Input) GetPublished() *bool {
	if p == nil {
		return nil
	}
	return p.Published
}

func (p *PageV4Input) GetVisibility() *Visibility {
	if p == nil {
		return nil
	}
	return p.Visibility
}

func (p *PageV4Input) GetUpdatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.UpdatedAt
}

func (p *PageV4Input) GetContentType() *string {
	if p == nil {
		return nil
	}
	return p.ContentType
}

func (p *PageV4Input) GetSource() *PageSource {
	if p == nil {
		return nil
	}
	return p.Source
}

func (p *PageV4Input) GetConfiguration() map[string]string {
	if p == nil {
		return nil
	}
	return p.Configuration
}

func (p *PageV4Input) GetHomepage() *bool {
	if p == nil {
		return nil
	}
	return p.Homepage
}

func (p *PageV4Input) GetParent() *string {
	if p == nil {
		return nil
	}
	return p.Parent
}

func (p *PageV4Input) GetAccessControls() []AccessControl {
	if p == nil {
		return nil
	}
	return p.AccessControls
}

func (p *PageV4Input) GetMetadata() map[string]string {
	if p == nil {
		return nil
	}
	return p.Metadata
}

func (p *PageV4Input) GetHidden() *bool {
	if p == nil {
		return nil
	}
	return p.Hidden
}

func (p *PageV4Input) GetTranslations() []PageV4TranslationInput {
	if p == nil {
		return nil
	}
	return p.Translations
}
