// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

// PageV4 - Documentation page.
type PageV4 struct {
	// Legacy API Page GUID for backward compatibility with GKO
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ID *string `json:"id,omitempty"`
	// A unique human readable id identifying this resource
	Hrid string `json:"hrid"`
	// Page's cross uuid.
	CrossID *string `json:"crossId,omitempty"`
	// This is the display name of the page in APIM and on the portal.
	// This field can be edited safely if you want to rename a page.
	//
	Name string `json:"name"`
	// The type of the documentation page or folder.
	Type PageType `json:"type"`
	// The content of the page, if any.
	Content *string `json:"content,omitempty"`
	// If true, the page will be accessible from the portal (default is false)
	Published *bool `default:"false" json:"published"`
	// The visibility of the entity regarding the portal.
	Visibility *Visibility `default:"PUBLIC" json:"visibility"`
	// Allow you to fetch pages from various external sources,
	// overriding page content each time the source is fetched.
	//
	Source *PageSource `json:"source,omitempty"`
	// Key/value page configuration (Configure swagger UI or or use Redoc instead)
	Configuration map[string]string `json:"configuration,omitempty"`
	// If true, this page will be displayed as the homepage of your API documentation.
	Homepage *bool `json:"homepage,omitempty"`
	// If your page contains a folder, setting this field to the folder's hrid will be reflected
	// into APIM by making the page a child of this folder.
	//
	ParentHrid *string `json:"parentHrid,omitempty"`
}

func (p PageV4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PageV4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PageV4) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PageV4) GetHrid() string {
	if p == nil {
		return ""
	}
	return p.Hrid
}

func (p *PageV4) GetCrossID() *string {
	if p == nil {
		return nil
	}
	return p.CrossID
}

func (p *PageV4) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PageV4) GetType() PageType {
	if p == nil {
		return PageType("")
	}
	return p.Type
}

func (p *PageV4) GetContent() *string {
	if p == nil {
		return nil
	}
	return p.Content
}

func (p *PageV4) GetPublished() *bool {
	if p == nil {
		return nil
	}
	return p.Published
}

func (p *PageV4) GetVisibility() *Visibility {
	if p == nil {
		return nil
	}
	return p.Visibility
}

func (p *PageV4) GetSource() *PageSource {
	if p == nil {
		return nil
	}
	return p.Source
}

func (p *PageV4) GetConfiguration() map[string]string {
	if p == nil {
		return nil
	}
	return p.Configuration
}

func (p *PageV4) GetHomepage() *bool {
	if p == nil {
		return nil
	}
	return p.Homepage
}

func (p *PageV4) GetParentHrid() *string {
	if p == nil {
		return nil
	}
	return p.ParentHrid
}
