// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"time"
)

// PageMedia - Page media
type PageMedia struct {
	// Media's name.
	Name *string `json:"name,omitempty"`
	// Media's hash.
	Hash *string `json:"hash,omitempty"`
	// Media's attachment date.
	AttachedAt *time.Time `json:"attachedAt,omitempty"`
}

func (p PageMedia) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PageMedia) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *PageMedia) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *PageMedia) GetHash() *string {
	if o == nil {
		return nil
	}
	return o.Hash
}

func (o *PageMedia) GetAttachedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.AttachedAt
}
