// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

// PathV4 - API Path specification
type PathV4 struct {
	// Virtual host required to access this API. (`Host` or `:Authority` headers, remote address for websockets)
	Host *string `json:"host,omitempty"`
	Path *string `default:"/" json:"path"`
	// Override default organization entrypoint with `host`
	OverrideAccess *bool `default:"false" json:"overrideAccess"`
}

func (p PathV4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PathV4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PathV4) GetHost() *string {
	if p == nil {
		return nil
	}
	return p.Host
}

func (p *PathV4) GetPath() *string {
	if p == nil {
		return nil
	}
	return p.Path
}

func (p *PathV4) GetOverrideAccess() *bool {
	if p == nil {
		return nil
	}
	return p.OverrideAccess
}
