// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

// PathV4 - API Path
type PathV4 struct {
	Host           *string `json:"host,omitempty"`
	Path           *string `default:"/" json:"path"`
	OverrideAccess *bool   `default:"false" json:"overrideAccess"`
}

func (p PathV4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PathV4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *PathV4) GetHost() *string {
	if o == nil {
		return nil
	}
	return o.Host
}

func (o *PathV4) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}

func (o *PathV4) GetOverrideAccess() *bool {
	if o == nil {
		return nil
	}
	return o.OverrideAccess
}
