// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Plan struct {
	// Unique identifier for the plan
	ID *string `json:"id,omitempty"`
	// Cross-reference ID
	CrossID           *string       `json:"crossId,omitempty"`
	Name              *string       `json:"name,omitempty"`
	Description       *string       `json:"description,omitempty"`
	Security          *PlanSecurity `json:"security,omitempty"`
	Characteristics   []string      `json:"characteristics,omitempty"`
	ExcludedGroups    []string      `json:"excludedGroups,omitempty"`
	GeneralConditions *string       `json:"generalConditions,omitempty"`
	Order             *int64        `json:"order,omitempty"`
	SelectionRule     *string       `json:"selectionRule,omitempty"`
	// Plan status.
	Status PlanStatus `json:"status"`
	Tags   []string   `json:"tags,omitempty"`
	// Plan type.
	Type PlanType `json:"type"`
	// Plan validation type.
	Validation *PlanValidation `json:"validation,omitempty"`
	Flows      []FlowV4        `json:"flows,omitempty"`
	// The behavioural mode of the Plan (Standard for classical plan, Push for subscription plan).
	Mode PlanMode `json:"mode"`
}

func (p *Plan) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *Plan) GetCrossID() *string {
	if p == nil {
		return nil
	}
	return p.CrossID
}

func (p *Plan) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *Plan) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *Plan) GetSecurity() *PlanSecurity {
	if p == nil {
		return nil
	}
	return p.Security
}

func (p *Plan) GetCharacteristics() []string {
	if p == nil {
		return nil
	}
	return p.Characteristics
}

func (p *Plan) GetExcludedGroups() []string {
	if p == nil {
		return nil
	}
	return p.ExcludedGroups
}

func (p *Plan) GetGeneralConditions() *string {
	if p == nil {
		return nil
	}
	return p.GeneralConditions
}

func (p *Plan) GetOrder() *int64 {
	if p == nil {
		return nil
	}
	return p.Order
}

func (p *Plan) GetSelectionRule() *string {
	if p == nil {
		return nil
	}
	return p.SelectionRule
}

func (p *Plan) GetStatus() PlanStatus {
	if p == nil {
		return PlanStatus("")
	}
	return p.Status
}

func (p *Plan) GetTags() []string {
	if p == nil {
		return nil
	}
	return p.Tags
}

func (p *Plan) GetType() PlanType {
	if p == nil {
		return PlanType("")
	}
	return p.Type
}

func (p *Plan) GetValidation() *PlanValidation {
	if p == nil {
		return nil
	}
	return p.Validation
}

func (p *Plan) GetFlows() []FlowV4 {
	if p == nil {
		return nil
	}
	return p.Flows
}

func (p *Plan) GetMode() PlanMode {
	if p == nil {
		return PlanMode("")
	}
	return p.Mode
}
