// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// PlanValidation - Usually specificies if subscriptions must be manually validated by a human actor.
// For automation API, it is disabled hence it is always set to `AUTO`.
type PlanValidation string

const (
	PlanValidationAuto PlanValidation = "AUTO"
)

func (e PlanValidation) ToPointer() *PlanValidation {
	return &e
}
func (e *PlanValidation) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AUTO":
		*e = PlanValidation(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PlanValidation: %v", v)
	}
}
