// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// PlanMode - The behavioural mode of the Plan (Standard for classical plan, Push for subscription plan).
type PlanMode string

const (
	PlanModeStandard PlanMode = "STANDARD"
	PlanModePush     PlanMode = "PUSH"
)

func (e PlanMode) ToPointer() *PlanMode {
	return &e
}
func (e *PlanMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "STANDARD":
		fallthrough
	case "PUSH":
		*e = PlanMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PlanMode: %v", v)
	}
}
