// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0164ab834c7c

package shared

// PortalNextThemeColor - Palette for a next-gen portal Theme.
type PortalNextThemeColor struct {
	// Primary color (CSS color value).
	Primary *string `json:"primary,omitempty"`
	// Secondary color (CSS color value).
	Secondary *string `json:"secondary,omitempty"`
	// Tertiary color (CSS color value).
	Tertiary *string `json:"tertiary,omitempty"`
	// Error color (CSS color value).
	Error *string `json:"error,omitempty"`
	// Background palette for a next-gen portal Theme.
	Background *PortalNextThemeBackground `json:"background,omitempty"`
}

func (p *PortalNextThemeColor) GetPrimary() *string {
	if p == nil {
		return nil
	}
	return p.Primary
}

func (p *PortalNextThemeColor) GetSecondary() *string {
	if p == nil {
		return nil
	}
	return p.Secondary
}

func (p *PortalNextThemeColor) GetTertiary() *string {
	if p == nil {
		return nil
	}
	return p.Tertiary
}

func (p *PortalNextThemeColor) GetError() *string {
	if p == nil {
		return nil
	}
	return p.Error
}

func (p *PortalNextThemeColor) GetBackground() *PortalNextThemeBackground {
	if p == nil {
		return nil
	}
	return p.Background
}
