// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3936be29e409

package shared

// PortalThemeSpec - Specification of a next-gen portal Theme. Applying a Theme through the Automation API
// makes it the active Theme for the environment; every other Theme in the same environment
// is disabled.
type PortalThemeSpec struct {
	// A unique human readable id identifying this resource
	Hrid string `json:"hrid"`
	// Display name of the theme
	Name string `json:"name"`
	// Visual definition of a next-gen portal Theme.
	Definition PortalNextThemeDefinition `json:"definition"`
	// Primary logo. Inline data URI (for example `data:image/png;base64,...`), the same shape the
	// console produces on upload.
	//
	Logo *string `json:"logo,omitempty"`
	// Alternate logo for contexts where the primary one does not render well (dark background, small badge, etc.).
	OptionalLogo *string `json:"optionalLogo,omitempty"`
	// Browser tab icon. Same inline data URI convention as `logo`.
	Favicon *string `json:"favicon,omitempty"`
	// Hero / landing page background image. Same inline data URI convention as `logo`.
	BackgroundImage *string `json:"backgroundImage,omitempty"`
}

func (p *PortalThemeSpec) GetHrid() string {
	if p == nil {
		return ""
	}
	return p.Hrid
}

func (p *PortalThemeSpec) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PortalThemeSpec) GetDefinition() PortalNextThemeDefinition {
	if p == nil {
		return PortalNextThemeDefinition{}
	}
	return p.Definition
}

func (p *PortalThemeSpec) GetLogo() *string {
	if p == nil {
		return nil
	}
	return p.Logo
}

func (p *PortalThemeSpec) GetOptionalLogo() *string {
	if p == nil {
		return nil
	}
	return p.OptionalLogo
}

func (p *PortalThemeSpec) GetFavicon() *string {
	if p == nil {
		return nil
	}
	return p.Favicon
}

func (p *PortalThemeSpec) GetBackgroundImage() *string {
	if p == nil {
		return nil
	}
	return p.BackgroundImage
}
