// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ConfigType string

const (
	ConfigTypePortal  ConfigType = "PORTAL"
	ConfigTypeGeneric ConfigType = "GENERIC"
)

func (e ConfigType) ToPointer() *ConfigType {
	return &e
}
func (e *ConfigType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PORTAL":
		fallthrough
	case "GENERIC":
		*e = ConfigType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConfigType: %v", v)
	}
}

type PortalNotificationConfig struct {
	ConfigType    ConfigType `json:"config_type"`
	Name          string     `json:"name"`
	ReferenceType *string    `json:"referenceType,omitempty"`
	ReferenceID   *string    `json:"referenceId,omitempty"`
	User          *string    `json:"user,omitempty"`
	Hooks         []string   `json:"hooks,omitempty"`
	Groups        []string   `json:"groups,omitempty"`
}

func (o *PortalNotificationConfig) GetConfigType() ConfigType {
	if o == nil {
		return ConfigType("")
	}
	return o.ConfigType
}

func (o *PortalNotificationConfig) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *PortalNotificationConfig) GetReferenceType() *string {
	if o == nil {
		return nil
	}
	return o.ReferenceType
}

func (o *PortalNotificationConfig) GetReferenceID() *string {
	if o == nil {
		return nil
	}
	return o.ReferenceID
}

func (o *PortalNotificationConfig) GetUser() *string {
	if o == nil {
		return nil
	}
	return o.User
}

func (o *PortalNotificationConfig) GetHooks() []string {
	if o == nil {
		return nil
	}
	return o.Hooks
}

func (o *PortalNotificationConfig) GetGroups() []string {
	if o == nil {
		return nil
	}
	return o.Groups
}
