// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c6755d79c636

package shared

// PortalState - State of a Portal that has been created/updated.
type PortalState struct {
	// A unique human readable id identifying this resource
	Hrid string `json:"hrid"`
	// Display name of the portal
	Name string `json:"name"`
	// Portal navigation grouped by area.
	Structure *PortalNavigationStructure `json:"structure,omitempty"`
	// Deprecated. Use `structure.topNavbar` instead. `navigation` and `structure` cannot be set at the same time;
	// when only `navigation` is provided, it is mapped to `structure.topNavbar` for backward compatibility.
	//
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Navigation []PortalNavigationPath `json:"navigation,omitempty"`
	// HRID of the Theme this portal should use as its active theme. When set, applying the portal
	// marks the referenced theme as active (enabled) and disables every other PORTAL_NEXT theme
	// in the environment. Leaving this field unset clears the reference and disables the
	// previously-active theme; the portal-next UI will then lazily fall back to a fresh default theme.
	//
	ActiveThemeHrid *string `json:"activeThemeHrid,omitempty"`
	// Resource UUID.
	ID *string `json:"id,omitempty"`
	// The environment ID.
	EnvironmentID *string `json:"environmentId,omitempty"`
	// The organization ID.
	OrganizationID *string `json:"organizationId,omitempty"`
	// When a resource has been created regardless of errors, this field is used to persist the error message encountered during validation
	Errors *Errors `json:"errors,omitempty"`
}

func (p *PortalState) GetHrid() string {
	if p == nil {
		return ""
	}
	return p.Hrid
}

func (p *PortalState) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PortalState) GetStructure() *PortalNavigationStructure {
	if p == nil {
		return nil
	}
	return p.Structure
}

func (p *PortalState) GetNavigation() []PortalNavigationPath {
	if p == nil {
		return nil
	}
	return p.Navigation
}

func (p *PortalState) GetActiveThemeHrid() *string {
	if p == nil {
		return nil
	}
	return p.ActiveThemeHrid
}

func (p *PortalState) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PortalState) GetEnvironmentID() *string {
	if p == nil {
		return nil
	}
	return p.EnvironmentID
}

func (p *PortalState) GetOrganizationID() *string {
	if p == nil {
		return nil
	}
	return p.OrganizationID
}

func (p *PortalState) GetErrors() *Errors {
	if p == nil {
		return nil
	}
	return p.Errors
}
