// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 17401b3aa275

package shared

// PortalListingState - State of a Portal Listing that has been created/updated.
type PortalListingState struct {
	// Resource UUID.
	ID *string `json:"id,omitempty"`
	// The environment ID.
	EnvironmentID *string `json:"environmentId,omitempty"`
	// The organization ID.
	OrganizationID *string `json:"organizationId,omitempty"`
	// When a resource has been created regardless of errors, this field is used to persist the error message encountered during validation
	Errors *Errors `json:"errors,omitempty"`
	// The HRID of the portal this listing belongs to.
	PortalHrid *string `json:"portalHrid,omitempty"`
	// A unique human readable id identifying this resource
	Hrid string `json:"hrid"`
	// List of APIs to publish to the portal. Use each entry's order to control display order relative to siblings at the same location.
	Apis []PortalListingAPIEntry `json:"apis"`
}

func (p *PortalListingState) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PortalListingState) GetEnvironmentID() *string {
	if p == nil {
		return nil
	}
	return p.EnvironmentID
}

func (p *PortalListingState) GetOrganizationID() *string {
	if p == nil {
		return nil
	}
	return p.OrganizationID
}

func (p *PortalListingState) GetErrors() *Errors {
	if p == nil {
		return nil
	}
	return p.Errors
}

func (p *PortalListingState) GetPortalHrid() *string {
	if p == nil {
		return nil
	}
	return p.PortalHrid
}

func (p *PortalListingState) GetHrid() string {
	if p == nil {
		return ""
	}
	return p.Hrid
}

func (p *PortalListingState) GetApis() []PortalListingAPIEntry {
	if p == nil {
		return []PortalListingAPIEntry{}
	}
	return p.Apis
}
