// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Property struct {
	Key         string `json:"key"`
	Value       string `json:"value"`
	Encrypted   *bool  `json:"encrypted,omitempty"`
	Dynamic     *bool  `json:"dynamic,omitempty"`
	Encryptable *bool  `json:"encryptable,omitempty"`
}

func (o *Property) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *Property) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}

func (o *Property) GetEncrypted() *bool {
	if o == nil {
		return nil
	}
	return o.Encrypted
}

func (o *Property) GetDynamic() *bool {
	if o == nil {
		return nil
	}
	return o.Dynamic
}

func (o *Property) GetEncryptable() *bool {
	if o == nil {
		return nil
	}
	return o.Encryptable
}
