// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// Qos - Type of the quality of service (for message APIs).
type Qos string

const (
	QosNone        Qos = "NONE"
	QosAuto        Qos = "AUTO"
	QosAtMostOnce  Qos = "AT_MOST_ONCE"
	QosAtLeastOnce Qos = "AT_LEAST_ONCE"
)

func (e Qos) ToPointer() *Qos {
	return &e
}
func (e *Qos) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NONE":
		fallthrough
	case "AUTO":
		fallthrough
	case "AT_MOST_ONCE":
		fallthrough
	case "AT_LEAST_ONCE":
		*e = Qos(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Qos: %v", v)
	}
}
