// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Resource struct {
	Name          string `json:"name"`
	Type          string `json:"type"`
	Configuration any    `json:"configuration"`
	Enabled       *bool  `json:"enabled,omitempty"`
}

func (o *Resource) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Resource) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *Resource) GetConfiguration() any {
	if o == nil {
		return nil
	}
	return o.Configuration
}

func (o *Resource) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}
