// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

// ResponseTemplate - API response template
type ResponseTemplate struct {
	// API response template status
	Status *int64 `json:"status,omitempty"`
	// API response template headers
	Headers map[string]string `json:"headers,omitempty"`
	// API response template body
	Body                    *string `json:"body,omitempty"`
	PropagateErrorKeyToLogs *bool   `default:"false" json:"propagateErrorKeyToLogs"`
}

func (r ResponseTemplate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ResponseTemplate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ResponseTemplate) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *ResponseTemplate) GetHeaders() map[string]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *ResponseTemplate) GetBody() *string {
	if o == nil {
		return nil
	}
	return o.Body
}

func (o *ResponseTemplate) GetPropagateErrorKeyToLogs() *bool {
	if o == nil {
		return nil
	}
	return o.PropagateErrorKeyToLogs
}
