// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

type ResponseTemplate struct {
	Status                  *int64            `json:"status,omitempty"`
	Headers                 map[string]string `json:"headers,omitempty"`
	Body                    *string           `json:"body,omitempty"`
	PropagateErrorKeyToLogs *bool             `default:"false" json:"propagateErrorKeyToLogs"`
}

func (r ResponseTemplate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ResponseTemplate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ResponseTemplate) GetStatus() *int64 {
	if r == nil {
		return nil
	}
	return r.Status
}

func (r *ResponseTemplate) GetHeaders() map[string]string {
	if r == nil {
		return nil
	}
	return r.Headers
}

func (r *ResponseTemplate) GetBody() *string {
	if r == nil {
		return nil
	}
	return r.Body
}

func (r *ResponseTemplate) GetPropagateErrorKeyToLogs() *bool {
	if r == nil {
		return nil
	}
	return r.PropagateErrorKeyToLogs
}
