// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// Revision - Page revision
type Revision struct {
	// Id of the page used to fill the content attributes.
	ID *string `json:"id,omitempty"`
	// Revision number.
	Revision *int64 `json:"revision,omitempty"`
}

func (o *Revision) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Revision) GetRevision() *int64 {
	if o == nil {
		return nil
	}
	return o.Revision
}
