// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

// ServiceV4 - Service
type ServiceV4 struct {
	// Override the configuration of the service
	OverrideConfiguration *bool `default:"false" json:"overrideConfiguration"`
	// The configuration of the service
	Configuration any `json:"configuration,omitempty"`
	// Is the service enabled or not.
	Enabled *bool   `default:"true" json:"enabled"`
	Type    *string `json:"type,omitempty"`
}

func (s ServiceV4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *ServiceV4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *ServiceV4) GetOverrideConfiguration() *bool {
	if s == nil {
		return nil
	}
	return s.OverrideConfiguration
}

func (s *ServiceV4) GetConfiguration() any {
	if s == nil {
		return nil
	}
	return s.Configuration
}

func (s *ServiceV4) GetEnabled() *bool {
	if s == nil {
		return nil
	}
	return s.Enabled
}

func (s *ServiceV4) GetType() *string {
	if s == nil {
		return nil
	}
	return s.Type
}
