// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
	"time"
)

// SubscriptionState - State of subscription that has been created/update
type SubscriptionState struct {
	// A unique human readable id identifying this resource
	Hrid string `json:"hrid"`
	// Application's Hrid that needs to subscribe to the API.
	ApplicationHrid string `json:"applicationHrid"`
	// API plan's Hrid
	PlanHrid string     `json:"planHrid"`
	EndingAt *time.Time `json:"endingAt,omitempty"`
	// When a resource has been created regardless of errors, this field is used to persist the error message encountered during validation
	Errors *Errors `json:"errors,omitempty"`
	// Subscription's uuid.
	ID *string `json:"id,omitempty"`
	// The API's Hrid.
	APIHrid    string     `json:"apiHrid"`
	StartingAt *time.Time `json:"startingAt,omitempty"`
}

func (s SubscriptionState) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubscriptionState) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"hrid", "applicationHrid", "planHrid", "apiHrid"}); err != nil {
		return err
	}
	return nil
}

func (s *SubscriptionState) GetHrid() string {
	if s == nil {
		return ""
	}
	return s.Hrid
}

func (s *SubscriptionState) GetApplicationHrid() string {
	if s == nil {
		return ""
	}
	return s.ApplicationHrid
}

func (s *SubscriptionState) GetPlanHrid() string {
	if s == nil {
		return ""
	}
	return s.PlanHrid
}

func (s *SubscriptionState) GetEndingAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.EndingAt
}

func (s *SubscriptionState) GetErrors() *Errors {
	if s == nil {
		return nil
	}
	return s.Errors
}

func (s *SubscriptionState) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *SubscriptionState) GetAPIHrid() string {
	if s == nil {
		return ""
	}
	return s.APIHrid
}

func (s *SubscriptionState) GetStartingAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.StartingAt
}
