// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

// SubscriptionListener - Subscription listener
type SubscriptionListener struct {
	// Listener type.
	Type        ListenerType `json:"type"`
	Entrypoints []Entrypoint `json:"entrypoints,omitempty"`
	Servers     []string     `json:"servers,omitempty"`
}

func (s SubscriptionListener) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubscriptionListener) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (s *SubscriptionListener) GetType() ListenerType {
	if s == nil {
		return ListenerType("")
	}
	return s.Type
}

func (s *SubscriptionListener) GetEntrypoints() []Entrypoint {
	if s == nil {
		return nil
	}
	return s.Entrypoints
}

func (s *SubscriptionListener) GetServers() []string {
	if s == nil {
		return nil
	}
	return s.Servers
}
