// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

type TCPListener struct {
	// Listener type.
	Type        ListenerType `json:"type"`
	Entrypoints []Entrypoint `json:"entrypoints,omitempty"`
	Servers     []string     `json:"servers,omitempty"`
	// A list of hostnames for which the API will match against SNI.  This must be unique for all TCP listener for a given server id. See 'servers' attribute
	Hosts []string `json:"hosts"`
}

func (t TCPListener) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TCPListener) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"type", "hosts"}); err != nil {
		return err
	}
	return nil
}

func (t *TCPListener) GetType() ListenerType {
	if t == nil {
		return ListenerType("")
	}
	return t.Type
}

func (t *TCPListener) GetEntrypoints() []Entrypoint {
	if t == nil {
		return nil
	}
	return t.Entrypoints
}

func (t *TCPListener) GetServers() []string {
	if t == nil {
		return nil
	}
	return t.Servers
}

func (t *TCPListener) GetHosts() []string {
	if t == nil {
		return []string{}
	}
	return t.Hosts
}
