// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// TracingV4 - API analytic tracing
type TracingV4 struct {
	// Enable OpenTelemetry tracing
	Enabled *bool `json:"enabled,omitempty"`
	// Enable technical tracing to get more details on request execution. Be careful this settings would generate more noise and would impact performance.
	Verbose *bool `json:"verbose,omitempty"`
}

func (t *TracingV4) GetEnabled() *bool {
	if t == nil {
		return nil
	}
	return t.Enabled
}

func (t *TracingV4) GetVerbose() *bool {
	if t == nil {
		return nil
	}
	return t.Verbose
}
