name: restore-docker-image
description: Resolve a Docker cache key and restore the image from cache in a single step.
inputs:
  image-name:
    description: The Docker image name (e.g. apim-management-api, mongo)
    required: true
  image-tag:
    description: The Docker image tag (e.g. master-latest, 4.9.x-latest)
    required: true
runs:
  using: 'composite'
  steps:
    - name: Resolve cache key
      id: resolve
      uses: ./.github/actions/resolve-cache-key
      with:
        image-name: ${{ inputs.image-name }}
        image-tag: ${{ inputs.image-tag }}
    - name: Restore Docker image cache
      id: docker-cache
      uses: actions/cache/restore@v4
      with:
        path: /tmp/docker-images.tar
        key: ${{ steps.resolve.outputs.value }}
    - name: Load Docker images from cache
      if: steps.docker-cache.outputs.cache-hit == 'true'
      shell: bash
      run: docker load -i /tmp/docker-images.tar
