workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Gravitee.io - Automation API:
        inputs:
            - location: schemas/automation-api-oas.yaml
        overlays:
            - location: schemas/overlay.yaml
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: schemas/output-oas.yaml
        registry:
            location: registry.speakeasyapi.dev/gravitee/gravitee/gravitee-io-gko---automation-api
targets:
    apim:
        target: terraform
        source: Gravitee.io - Automation API
