workflowVersion: 1.0.0
speakeasyVersion: 1.697.5
sources:
    automation-api:
        inputs:
            - location: schemas/automation-api-oas.yaml
        overlays:
            - location: schemas/overlays/oas-core.yaml
            - location: schemas/overlays/common-param.yaml
            - location: schemas/overlays/common-schema.yaml
            - location: schemas/overlays/apiv4.yaml
            - location: schemas/overlays/shared-policy-group.yaml
            - location: schemas/overlays/application.yaml
            - location: schemas/overlays/subscription.yaml
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: schemas/output/computed.yaml
        registry:
            location: registry.speakeasyapi.dev/gravitee/gravitee/gravitee-io-gko---automation-api
targets:
    apim:
        target: terraform
        source: automation-api
