workflowVersion: 1.0.0
speakeasyVersion: 1.764.0
sources:
    automation-api:
        inputs:
            - location: automation-api-oas.yaml
        overlays:
            - location: .speakeasy/overlays/common/oas.yaml
            - location: .speakeasy/overlays/common/param.yaml
            - location: .speakeasy/overlays/common/schema.yaml
            - location: .speakeasy/overlays/apiv4.yaml
            - location: .speakeasy/overlays/shared-policy-group.yaml
            - location: .speakeasy/overlays/application.yaml
            - location: .speakeasy/overlays/subscription.yaml
            - location: .speakeasy/overlays/dictionary.yaml
            - location: .speakeasy/overlays/group.yaml
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/output/computed.yaml
        registry:
            location: registry.speakeasyapi.dev/gravitee/gravitee/gravitee-io-gko---automation-api
targets:
    apim:
        target: terraform
        source: automation-api
