name: pull-docker-image
description: Resolve the full image reference and pull it from the registry.
inputs:
  image-name:
    description: The Docker image name (e.g. apim-management-api, mongo)
    required: true
  image-tag:
    description: The Docker image tag (e.g. master-latest, 7.0.23-jammy)
    required: true
runs:
  using: 'composite'
  steps:
    - name: Resolve cache key
      id: resolve
      uses: ./.github/actions/resolve-cache-key
      with:
        image-name: ${{ inputs.image-name }}
        image-tag: ${{ inputs.image-tag }}
    - name: Resolve image reference
      id: images
      shell: bash
      run: |
        if [[ "${{ inputs.image-name }}" == "mongo" ]]; then
          echo "ref=${{ inputs.image-name }}:${{ inputs.image-tag }}" >> "$GITHUB_OUTPUT"
        else
          REGISTRY=$(yq '.apim.image.registry' hack/apim.yaml)
          echo "ref=${REGISTRY}/${{ inputs.image-name }}:${{ inputs.image-tag }}" >> "$GITHUB_OUTPUT"
        fi
    - name: Pull image
      shell: bash
      run: docker pull "${{ steps.images.outputs.ref }}"
    - name: Save image cache
      uses: ./.github/actions/docker-cache-save
      with:
        cache-key: ${{ steps.resolve.outputs.value }}
        images: ${{ steps.images.outputs.ref }}
