// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4903f0ba16b5

package provider

import (
	"context"
	"fmt"
	tfTypes "github.com/gravitee-io/terraform-provider-apim/internal/provider/types"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"regexp"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &DictionaryDataSource{}
var _ datasource.DataSourceWithConfigure = &DictionaryDataSource{}

func NewDictionaryDataSource() datasource.DataSource {
	return &DictionaryDataSource{}
}

// DictionaryDataSource is the data source implementation.
type DictionaryDataSource struct {
	// Provider configured SDK client.
	client *sdk.GraviteeApim

	// environment ID
	EnvironmentID types.String `tfsdk:"environment_id"`

	// organization ID
	OrganizationID types.String `tfsdk:"organization_id"`
}

// DictionaryDataSourceModel describes the data model.
type DictionaryDataSourceModel struct {
	Deployed       types.Bool                     `tfsdk:"deployed"`
	Description    types.String                   `tfsdk:"description"`
	Dynamic        *tfTypes.DynamicDictionarySpec `tfsdk:"dynamic"`
	EnvironmentID  types.String                   `tfsdk:"environment_id"`
	Hrid           types.String                   `tfsdk:"hrid"`
	ID             types.String                   `tfsdk:"id"`
	Manual         *tfTypes.ManualDictionarySpec  `tfsdk:"manual"`
	Name           types.String                   `tfsdk:"name"`
	OrganizationID types.String                   `tfsdk:"organization_id"`
	Type           types.String                   `tfsdk:"type"`
}

// Metadata returns the data source type name.
func (r *DictionaryDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dictionary"
}

// Schema defines the schema for the data source.
func (r *DictionaryDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Dictionary DataSource",

		Attributes: map[string]schema.Attribute{
			"deployed": schema.BoolAttribute{
				Computed: true,
				MarkdownDescription: `If true, a ` + "`" + `MANUAL` + "`" + ` type dictionary is deployed in the gateway, a ` + "`" + `DYNAMIC` + "`" + ` type dictionary is started. ` + "\n" +
					`Changing this value back to false will stop the dictionary or undeploy it.`,
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Description: `Detailed description of the dictionary`,
			},
			"dynamic": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"provider": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"http": schema.SingleNestedAttribute{
								Computed: true,
								Attributes: map[string]schema.Attribute{
									"body": schema.StringAttribute{
										Computed:    true,
										Description: `Optional request payload`,
									},
									"headers": schema.ListNestedAttribute{
										Computed: true,
										NestedObject: schema.NestedAttributeObject{
											Attributes: map[string]schema.Attribute{
												"name": schema.StringAttribute{
													Computed:    true,
													Description: `Header name`,
												},
												"value": schema.StringAttribute{
													Computed:    true,
													Description: `Header value`,
												},
											},
										},
										Description: `HTTP Headers`,
									},
									"method": schema.StringAttribute{
										Computed: true,
									},
									"specification": schema.StringAttribute{
										Computed:    true,
										Description: `Transformation of the returned payload (JOLT Specification)`,
									},
									"type": schema.StringAttribute{
										Computed:    true,
										Description: `Type of dictionary provider.`,
									},
									"url": schema.StringAttribute{
										Computed:    true,
										Sensitive:   true,
										Description: `URL of the provider`,
									},
									"use_system_proxy": schema.BoolAttribute{
										Computed: true,
									},
								},
								Description: `HTTP dictionary provider configuration`,
							},
						},
						Description: `Provider of a 'DYNAMIC' type dictionary`,
					},
					"trigger": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"rate": schema.Int64Attribute{
								Computed: true,
							},
							"unit": schema.StringAttribute{
								Computed: true,
							},
						},
						Description: `Renewal configuration for a 'DYNAMIC' dictionary`,
					},
				},
				Description: `A dynamic dictionary populated from an external provider on a schedule.`,
			},
			"environment_id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: `The environment ID of the API.`,
			},
			"hrid": schema.StringAttribute{
				Required:    true,
				Description: `A unique human readable id identifying this resource`,
				Validators: []validator.String{
					stringvalidator.UTF8LengthAtMost(256),
					stringvalidator.RegexMatches(regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9_-]+[a-zA-Z0-9]$`), "must match pattern "+regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9_-]+[a-zA-Z0-9]$`).String()),
				},
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"manual": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"properties": schema.MapAttribute{
						Computed:    true,
						ElementType: types.StringType,
						Description: `Dictionary data are key/value pairs for ` + "`" + `MANUAL` + "`" + ` properties`,
					},
				},
				Description: `A manual dictionary with static key/value properties.`,
			},
			"name": schema.StringAttribute{
				Computed:    true,
				Description: `Display name of the dictionary`,
			},
			"organization_id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: `The organization ID of the API.`,
			},
			"type": schema.StringAttribute{
				Computed:    true,
				Description: `Type of dictionary. MANUAL is to be updated manually, DYNAMIC is updated and deployed automatically.`,
			},
		},
	}
}

func (r *DictionaryDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*ApimProviderConfigureData)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *ApimProviderConfigureData, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.EnvironmentID = providerData.EnvironmentID
	r.OrganizationID = providerData.OrganizationID
	r.client = providerData.SDKClient
}

func (r *DictionaryDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *DictionaryDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	if (data.EnvironmentID.IsNull() || data.EnvironmentID.IsUnknown()) && !r.EnvironmentID.IsUnknown() {
		data.EnvironmentID = r.EnvironmentID
	}

	if (data.OrganizationID.IsNull() || data.OrganizationID.IsUnknown()) && !r.OrganizationID.IsUnknown() {
		data.OrganizationID = r.OrganizationID
	}

	request, requestDiags := data.ToOperationsGetDictionaryRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Dictionaries.GetDictionary(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.DictionaryState != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedDictionaryState(ctx, res.DictionaryState)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
