// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 318ed979ef04

package provider

import (
	"context"
	tfTypes "github.com/gravitee-io/terraform-provider-apim/internal/provider/types"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/operations"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *GroupResourceModel) RefreshFromSharedGroupState(ctx context.Context, resp *shared.GroupState) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if resp.DefaultMemberRoles == nil {
			r.DefaultMemberRoles = nil
		} else {
			r.DefaultMemberRoles = &tfTypes.GroupDefaultMemberRoles{}
			r.DefaultMemberRoles.API = types.StringPointerValue(resp.DefaultMemberRoles.API)
			r.DefaultMemberRoles.APIProduct = types.StringPointerValue(resp.DefaultMemberRoles.APIProduct)
			r.DefaultMemberRoles.Application = types.StringPointerValue(resp.DefaultMemberRoles.Application)
		}
		r.EnvironmentID = types.StringPointerValue(resp.EnvironmentID)
		r.Hrid = types.StringValue(resp.Hrid)
		r.ID = types.StringPointerValue(resp.ID)
		r.Members = []tfTypes.GroupMember{}

		for _, membersItem := range resp.Members {
			var members tfTypes.GroupMember

			if len(membersItem.Roles) > 0 {
				members.Roles = make(map[string]types.String, len(membersItem.Roles))
				for key, value := range membersItem.Roles {
					members.Roles[key] = types.StringValue(value)
				}
			}
			members.Source = types.StringValue(membersItem.Source)
			members.SourceID = types.StringValue(membersItem.SourceID)

			r.Members = append(r.Members, members)
		}
		r.Name = types.StringValue(resp.Name)
		r.NotifyMembers = types.BoolPointerValue(resp.NotifyMembers)
		r.OrganizationID = types.StringPointerValue(resp.OrganizationID)
	}

	return diags
}

func (r *GroupResourceModel) ToOperationsCreateOrUpdateGroupRequest(ctx context.Context) (*operations.CreateOrUpdateGroupRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	ignoreMembers := new(bool)
	if !r.IgnoreMembers.IsUnknown() && !r.IgnoreMembers.IsNull() {
		*ignoreMembers = r.IgnoreMembers.ValueBool()
	} else {
		ignoreMembers = nil
	}
	groupSpec, groupSpecDiags := r.ToSharedGroupSpec(ctx)
	diags.Append(groupSpecDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.CreateOrUpdateGroupRequest{
		OrganizationID: organizationID,
		EnvironmentID:  environmentID,
		IgnoreMembers:  ignoreMembers,
		GroupSpec:      *groupSpec,
	}

	return &out, diags
}

func (r *GroupResourceModel) ToOperationsDeleteGroupRequest(ctx context.Context) (*operations.DeleteGroupRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var hrid string
	hrid = r.Hrid.ValueString()

	out := operations.DeleteGroupRequest{
		OrganizationID: organizationID,
		EnvironmentID:  environmentID,
		Hrid:           hrid,
	}

	return &out, diags
}

func (r *GroupResourceModel) ToOperationsGetGroupRequest(ctx context.Context) (*operations.GetGroupRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var hrid string
	hrid = r.Hrid.ValueString()

	out := operations.GetGroupRequest{
		OrganizationID: organizationID,
		EnvironmentID:  environmentID,
		Hrid:           hrid,
	}

	return &out, diags
}

func (r *GroupResourceModel) ToSharedGroupSpec(ctx context.Context) (*shared.GroupSpec, diag.Diagnostics) {
	var diags diag.Diagnostics

	var hrid string
	hrid = r.Hrid.ValueString()

	var name string
	name = r.Name.ValueString()

	members := make([]shared.GroupMember, 0, len(r.Members))
	for membersIndex := range r.Members {
		var source string
		source = r.Members[membersIndex].Source.ValueString()

		var sourceID string
		sourceID = r.Members[membersIndex].SourceID.ValueString()

		roles := make(map[string]string)
		for rolesKey := range r.Members[membersIndex].Roles {
			var rolesInst string
			rolesInst = r.Members[membersIndex].Roles[rolesKey].ValueString()

			roles[rolesKey] = rolesInst
		}
		members = append(members, shared.GroupMember{
			Source:   source,
			SourceID: sourceID,
			Roles:    roles,
		})
	}
	var defaultMemberRoles *shared.GroupDefaultMemberRoles
	if r.DefaultMemberRoles != nil {
		api := new(string)
		if !r.DefaultMemberRoles.API.IsUnknown() && !r.DefaultMemberRoles.API.IsNull() {
			*api = r.DefaultMemberRoles.API.ValueString()
		} else {
			api = nil
		}
		application := new(string)
		if !r.DefaultMemberRoles.Application.IsUnknown() && !r.DefaultMemberRoles.Application.IsNull() {
			*application = r.DefaultMemberRoles.Application.ValueString()
		} else {
			application = nil
		}
		apiProduct := new(string)
		if !r.DefaultMemberRoles.APIProduct.IsUnknown() && !r.DefaultMemberRoles.APIProduct.IsNull() {
			*apiProduct = r.DefaultMemberRoles.APIProduct.ValueString()
		} else {
			apiProduct = nil
		}
		defaultMemberRoles = &shared.GroupDefaultMemberRoles{
			API:         api,
			Application: application,
			APIProduct:  apiProduct,
		}
	}
	notifyMembers := new(bool)
	if !r.NotifyMembers.IsUnknown() && !r.NotifyMembers.IsNull() {
		*notifyMembers = r.NotifyMembers.ValueBool()
	} else {
		notifyMembers = nil
	}
	out := shared.GroupSpec{
		Hrid:               hrid,
		Name:               name,
		Members:            members,
		DefaultMemberRoles: defaultMemberRoles,
		NotifyMembers:      notifyMembers,
	}

	return &out, diags
}
