// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 318ed979ef04

package provider

import (
	"context"
	tfTypes "github.com/gravitee-io/terraform-provider-apim/internal/provider/types"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/operations"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *GroupResourceModel) RefreshFromSharedGroupState(ctx context.Context, resp *shared.GroupState) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Hrid = types.StringValue(resp.Hrid)
		r.ID = types.StringPointerValue(resp.ID)
		r.Members = []tfTypes.GroupMember{}

		for _, membersItem := range resp.Members {
			var members tfTypes.GroupMember

			if len(membersItem.Roles) > 0 {
				members.Roles = make(map[string]types.String, len(membersItem.Roles))
				for key, value := range membersItem.Roles {
					members.Roles[key] = types.StringValue(value)
				}
			}
			members.Source = types.StringValue(membersItem.Source)
			members.SourceID = types.StringValue(membersItem.SourceID)

			r.Members = append(r.Members, members)
		}
		r.Name = types.StringValue(resp.Name)
		r.NotifyMembers = types.BoolPointerValue(resp.NotifyMembers)
	}

	return diags
}

func (r *GroupResourceModel) ToOperationsCreateOrUpdateGroupRequest(ctx context.Context) (*operations.CreateOrUpdateGroupRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	hridContainsUUID := new(bool)
	if !r.HridContainsUUID.IsUnknown() && !r.HridContainsUUID.IsNull() {
		*hridContainsUUID = r.HridContainsUUID.ValueBool()
	} else {
		hridContainsUUID = nil
	}
	groupSpec, groupSpecDiags := r.ToSharedGroupSpec(ctx)
	diags.Append(groupSpecDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.CreateOrUpdateGroupRequest{
		OrganizationID:   organizationID,
		EnvironmentID:    environmentID,
		HridContainsUUID: hridContainsUUID,
		GroupSpec:        *groupSpec,
	}

	return &out, diags
}

func (r *GroupResourceModel) ToOperationsDeleteGroupRequest(ctx context.Context) (*operations.DeleteGroupRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var hrid string
	hrid = r.Hrid.ValueString()

	hridContainsUUID := new(bool)
	if !r.HridContainsUUID.IsUnknown() && !r.HridContainsUUID.IsNull() {
		*hridContainsUUID = r.HridContainsUUID.ValueBool()
	} else {
		hridContainsUUID = nil
	}
	out := operations.DeleteGroupRequest{
		OrganizationID:   organizationID,
		EnvironmentID:    environmentID,
		Hrid:             hrid,
		HridContainsUUID: hridContainsUUID,
	}

	return &out, diags
}

func (r *GroupResourceModel) ToOperationsGetGroupRequest(ctx context.Context) (*operations.GetGroupRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var hrid string
	hrid = r.Hrid.ValueString()

	hridContainsUUID := new(bool)
	if !r.HridContainsUUID.IsUnknown() && !r.HridContainsUUID.IsNull() {
		*hridContainsUUID = r.HridContainsUUID.ValueBool()
	} else {
		hridContainsUUID = nil
	}
	out := operations.GetGroupRequest{
		OrganizationID:   organizationID,
		EnvironmentID:    environmentID,
		Hrid:             hrid,
		HridContainsUUID: hridContainsUUID,
	}

	return &out, diags
}

func (r *GroupResourceModel) ToSharedGroupSpec(ctx context.Context) (*shared.GroupSpec, diag.Diagnostics) {
	var diags diag.Diagnostics

	var hrid string
	hrid = r.Hrid.ValueString()

	var name string
	name = r.Name.ValueString()

	members := make([]shared.GroupMember, 0, len(r.Members))
	for membersIndex := range r.Members {
		var source string
		source = r.Members[membersIndex].Source.ValueString()

		var sourceID string
		sourceID = r.Members[membersIndex].SourceID.ValueString()

		roles := make(map[string]string)
		for rolesKey := range r.Members[membersIndex].Roles {
			var rolesInst string
			rolesInst = r.Members[membersIndex].Roles[rolesKey].ValueString()

			roles[rolesKey] = rolesInst
		}
		members = append(members, shared.GroupMember{
			Source:   source,
			SourceID: sourceID,
			Roles:    roles,
		})
	}
	notifyMembers := new(bool)
	if !r.NotifyMembers.IsUnknown() && !r.NotifyMembers.IsNull() {
		*notifyMembers = r.NotifyMembers.ValueBool()
	} else {
		notifyMembers = nil
	}
	out := shared.GroupSpec{
		Hrid:          hrid,
		Name:          name,
		Members:       members,
		NotifyMembers: notifyMembers,
	}

	return &out, diags
}
