// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 843bedf73467

package provider

import (
	"context"
	"fmt"
	tfTypes "github.com/gravitee-io/terraform-provider-apim/internal/provider/types"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"regexp"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &McpProxyDataSource{}
var _ datasource.DataSourceWithConfigure = &McpProxyDataSource{}

func NewMcpProxyDataSource() datasource.DataSource {
	return &McpProxyDataSource{}
}

// McpProxyDataSource is the data source implementation.
type McpProxyDataSource struct {
	// Provider configured SDK client.
	client *sdk.GraviteeApim

	// environment ID
	EnvironmentID types.String `tfsdk:"environment_id"`

	// organization ID
	OrganizationID types.String `tfsdk:"organization_id"`
}

// McpProxyDataSourceModel describes the data model.
type McpProxyDataSourceModel struct {
	ContextPath       types.String                                `tfsdk:"context_path"`
	Description       types.String                                `tfsdk:"description"`
	EntityID          types.String                                `tfsdk:"entity_id"`
	EnvironmentID     types.String                                `tfsdk:"environment_id"`
	FlowExecution     *tfTypes.AimMcpProxyFlowExecution           `tfsdk:"flow_execution"`
	Flows             []tfTypes.AimMcpProxyFlow                   `tfsdk:"flows"`
	Hrid              types.String                                `tfsdk:"hrid"`
	ID                types.String                                `tfsdk:"id"`
	IdentityProviders []tfTypes.AimMcpProxyIdentityProviderOutput `tfsdk:"identity_providers"`
	Mode              types.String                                `tfsdk:"mode"`
	Name              types.String                                `tfsdk:"name"`
	OrganizationID    types.String                                `tfsdk:"organization_id"`
	Plans             []tfTypes.AimMcpProxyPlan                   `tfsdk:"plans"`
	Proxy             *tfTypes.AimMcpProxyStateProxy              `tfsdk:"proxy"`
	State             types.String                                `tfsdk:"state"`
	Studio            *tfTypes.AimMcpProxyStateStudio             `tfsdk:"studio"`
}

// Metadata returns the data source type name.
func (r *McpProxyDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mcp_proxy"
}

// Schema defines the schema for the data source.
func (r *McpProxyDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "McpProxy DataSource",

		Attributes: map[string]schema.Attribute{
			"context_path": schema.StringAttribute{
				Computed:    true,
				Description: `Context path the gateway serves the proxy on; must be available in the environment`,
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Description: `Human description of the proxy; converges on re-apply`,
			},
			"entity_id": schema.StringAttribute{
				Computed: true,
				MarkdownDescription: `Stable identity of the proxy, the name authorization policies reference: lowercase, dot-separated` + "\n" +
					`segments, first segment ` + "`" + `mcp-proxy` + "`" + `. Required. Validated,` + "\n" +
					`never repaired: an invalid value, or a value already used by another MCP proxy of the environment, is` + "\n" +
					`rejected. Immutable once the proxy exists — declaring a different value is rejected rather than` + "\n" +
					`applied. Delete the proxy and declare it again to give it another identity. Uniqueness across the` + "\n" +
					`environment is checked at apply time, not enforced by the store (AIAM-242): two concurrent applies` + "\n" +
					`of the same entityId can both pass.`,
			},
			"environment_id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: `The environment ID`,
			},
			"flow_execution": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"match_required": schema.BoolAttribute{
						Computed:    true,
						Description: `Reject a request no flow matches; false when omitted`,
					},
					"mode": schema.StringAttribute{
						Computed:    true,
						Description: `Flow selection mode`,
					},
				},
				MarkdownDescription: `How the gateway selects among the proxy's flows. ` + "`" + `DEFAULT` + "`" + ` runs every flow whose selectors match;` + "\n" +
					`` + "`" + `BEST_MATCH` + "`" + ` runs the one whose selectors match best. Omitted, APIM's defaults apply and the state` + "\n" +
					`reports no execution block.`,
			},
			"flows": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"enabled": schema.BoolAttribute{
							Computed:    true,
							Description: `Whether the gateway runs the flow; true when omitted`,
						},
						"name": schema.StringAttribute{
							Computed:    true,
							Description: `Name of the flow, shown in the policy studio; flows are compared by content, not by name`,
						},
						"request": schema.ListNestedAttribute{
							Computed: true,
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"condition": schema.StringAttribute{
										Computed:    true,
										Description: `Expression-language condition the step runs under; always when omitted`,
									},
									"configuration": schema.StringAttribute{
										CustomType:  jsontypes.NormalizedType{},
										Computed:    true,
										Description: `Configuration of the policy, free-form as the policy's own schema defines it; validated against that schema on apply and dry run. Parsed as JSON.`,
									},
									"description": schema.StringAttribute{
										Computed:    true,
										Description: `Human description of the step`,
									},
									"enabled": schema.BoolAttribute{
										Computed:    true,
										Description: `Whether the gateway runs the step; true when omitted`,
									},
									"name": schema.StringAttribute{
										Computed:    true,
										Description: `Name of the step, shown in the policy studio`,
									},
									"policy": schema.StringAttribute{
										Computed:    true,
										Description: `Id of a policy plugin deployed on the platform`,
									},
								},
							},
							Description: `Steps run on the request, in order`,
						},
						"response": schema.ListNestedAttribute{
							Computed: true,
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"condition": schema.StringAttribute{
										Computed:    true,
										Description: `Expression-language condition the step runs under; always when omitted`,
									},
									"configuration": schema.StringAttribute{
										CustomType:  jsontypes.NormalizedType{},
										Computed:    true,
										Description: `Configuration of the policy, free-form as the policy's own schema defines it; validated against that schema on apply and dry run. Parsed as JSON.`,
									},
									"description": schema.StringAttribute{
										Computed:    true,
										Description: `Human description of the step`,
									},
									"enabled": schema.BoolAttribute{
										Computed:    true,
										Description: `Whether the gateway runs the step; true when omitted`,
									},
									"name": schema.StringAttribute{
										Computed:    true,
										Description: `Name of the step, shown in the policy studio`,
									},
									"policy": schema.StringAttribute{
										Computed:    true,
										Description: `Id of a policy plugin deployed on the platform`,
									},
								},
							},
							Description: `Steps run on the response, in order`,
						},
						"selectors": schema.ListNestedAttribute{
							Computed: true,
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"condition": schema.SingleNestedAttribute{
										Computed: true,
										Attributes: map[string]schema.Attribute{
											"condition": schema.StringAttribute{
												Computed:    true,
												Description: `Condition the request must satisfy`,
											},
											"type": schema.StringAttribute{
												Computed:    true,
												Description: `Kind of selector`,
											},
										},
									},
									"mcp": schema.SingleNestedAttribute{
										Computed: true,
										Attributes: map[string]schema.Attribute{
											"methods": schema.ListAttribute{
												Computed:    true,
												ElementType: types.StringType,
												Description: `MCP methods the flow applies to, such as ` + "`" + `tools/call` + "`" + `; every method when empty`,
											},
											"type": schema.StringAttribute{
												Computed:    true,
												Description: `Kind of selector`,
											},
										},
									},
								},
							},
							Description: `What the flow applies to; a flow without selectors applies to every request`,
						},
						"tags": schema.ListAttribute{
							Computed:    true,
							ElementType: types.StringType,
							Description: `Sharding tags of the gateways the flow runs on; all of them when omitted`,
						},
					},
				},
				MarkdownDescription: `Policy flows of the proxy, in execution order, run after the flows of the plan the request matched.` + "\n" +
					`The manifest owns them: on every apply the proxy's flows are replaced by the declared ones, so a` + "\n" +
					`flow authored in the policy studio survives only if the manifest carries it, and omitting ` + "`" + `flows` + "`" + `` + "\n" +
					`removes them all. Each step's configuration is validated against its policy's schema, on apply and` + "\n" +
					`on dry run, and reported back as stored.`,
			},
			"hrid": schema.StringAttribute{
				Required:    true,
				Description: `A unique human readable id identifying this resource`,
				Validators: []validator.String{
					stringvalidator.UTF8LengthAtMost(256),
					stringvalidator.RegexMatches(regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9_-]+[a-zA-Z0-9]$`), "must match pattern "+regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9_-]+[a-zA-Z0-9]$`).String()),
				},
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Description: `Resource UUID`,
			},
			"identity_providers": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"gravitee_am": schema.SingleNestedAttribute{
							Computed: true,
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									Computed:    true,
									Description: `Name of the provider, the resource name on the proxy and the value plans reference`,
								},
								"type": schema.StringAttribute{
									Computed:    true,
									Description: `Kind of authorization server`,
								},
							},
						},
						"oauth2_auth0": schema.SingleNestedAttribute{
							Computed: true,
							Attributes: map[string]schema.Attribute{
								"audience": schema.StringAttribute{
									Computed:    true,
									Description: `Audience of the tokens the gateway accepts`,
								},
								"domain": schema.StringAttribute{
									Computed:    true,
									Description: `Auth0 tenant domain`,
								},
								"name": schema.StringAttribute{
									Computed:    true,
									Description: `Name of the provider, the resource name on the proxy and the value plans reference`,
								},
								"type": schema.StringAttribute{
									Computed:    true,
									Description: `Kind of authorization server`,
								},
							},
						},
						"oauth2_generic": schema.SingleNestedAttribute{
							Computed: true,
							Attributes: map[string]schema.Attribute{
								"client_id": schema.StringAttribute{
									Computed:    true,
									Description: `Client id the gateway introspects tokens with`,
								},
								"introspection_endpoint": schema.StringAttribute{
									Computed: true,
									MarkdownDescription: `Token introspection endpoint, as a path relative to ` + "`" + `issuerUrl` + "`" + ` or as an absolute URL beneath it;` + "\n" +
										`stored and reported as the path`,
								},
								"introspection_endpoint_method": schema.StringAttribute{
									Computed:    true,
									Description: `HTTP method of the introspection call`,
								},
								"issuer_url": schema.StringAttribute{
									Computed:    true,
									Description: `Issuer URL of the authorization server, the base the endpoints are resolved against`,
								},
								"name": schema.StringAttribute{
									Computed:    true,
									Description: `Name of the provider, the resource name on the proxy and the value plans reference`,
								},
								"type": schema.StringAttribute{
									Computed:    true,
									Description: `Kind of authorization server`,
								},
								"user_info_endpoint": schema.StringAttribute{
									Computed:    true,
									Description: `UserInfo endpoint, same rule as ` + "`" + `introspectionEndpoint` + "`" + ``,
								},
							},
						},
					},
				},
				MarkdownDescription: `Authorization servers declared on the proxy as OAuth2 resources, which OAUTH2 plans reference through` + "\n" +
					`` + "`" + `provider` + "`" + `. Converged by name: a declared provider the proxy lacks is attached; a declared provider` + "\n" +
					`whose configuration differs from the proxy's resource is rejected, except a generic provider's` + "\n" +
					`` + "`" + `clientSecret` + "`" + `, which replaces the stored one when it differs and is kept when omitted; a resource` + "\n" +
					`no longer declared is left in place; a declared provider named like a resource the proxy holds` + "\n" +
					`disabled, or under another type, is rejected. At most one ` + "`" + `GRAVITEE_AM` + "`" + ` provider, provisioned when` + "\n" +
					`the proxy is created only.`,
			},
			"mode": schema.StringAttribute{
				Computed: true,
				MarkdownDescription: `Shape of the proxy, and the one block it carries: ` + "`" + `PROXY` + "`" + ` fronts one upstream MCP server, declared under` + "\n" +
					`` + "`" + `proxy` + "`" + `; ` + "`" + `STUDIO` + "`" + ` composes a curated tool surface out of catalog MCP servers, declared under ` + "`" + `studio` + "`" + `. The` + "\n" +
					`other mode's block is rejected. Required. Fixed at creation: declaring another mode on` + "\n" +
					`an existing proxy is rejected, and changing it is a delete and a new declaration.`,
			},
			"name": schema.StringAttribute{
				Computed:    true,
				Description: `Display name of the proxy; converges on re-apply`,
			},
			"organization_id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: `The organization ID`,
			},
			"plans": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"flows": schema.ListNestedAttribute{
							Computed: true,
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"enabled": schema.BoolAttribute{
										Computed:    true,
										Description: `Whether the gateway runs the flow; true when omitted`,
									},
									"name": schema.StringAttribute{
										Computed:    true,
										Description: `Name of the flow, shown in the policy studio; flows are compared by content, not by name`,
									},
									"request": schema.ListNestedAttribute{
										Computed: true,
										NestedObject: schema.NestedAttributeObject{
											Attributes: map[string]schema.Attribute{
												"condition": schema.StringAttribute{
													Computed:    true,
													Description: `Expression-language condition the step runs under; always when omitted`,
												},
												"configuration": schema.StringAttribute{
													CustomType:  jsontypes.NormalizedType{},
													Computed:    true,
													Description: `Configuration of the policy, free-form as the policy's own schema defines it; validated against that schema on apply and dry run. Parsed as JSON.`,
												},
												"description": schema.StringAttribute{
													Computed:    true,
													Description: `Human description of the step`,
												},
												"enabled": schema.BoolAttribute{
													Computed:    true,
													Description: `Whether the gateway runs the step; true when omitted`,
												},
												"name": schema.StringAttribute{
													Computed:    true,
													Description: `Name of the step, shown in the policy studio`,
												},
												"policy": schema.StringAttribute{
													Computed:    true,
													Description: `Id of a policy plugin deployed on the platform`,
												},
											},
										},
										Description: `Steps run on the request, in order`,
									},
									"response": schema.ListNestedAttribute{
										Computed: true,
										NestedObject: schema.NestedAttributeObject{
											Attributes: map[string]schema.Attribute{
												"condition": schema.StringAttribute{
													Computed:    true,
													Description: `Expression-language condition the step runs under; always when omitted`,
												},
												"configuration": schema.StringAttribute{
													CustomType:  jsontypes.NormalizedType{},
													Computed:    true,
													Description: `Configuration of the policy, free-form as the policy's own schema defines it; validated against that schema on apply and dry run. Parsed as JSON.`,
												},
												"description": schema.StringAttribute{
													Computed:    true,
													Description: `Human description of the step`,
												},
												"enabled": schema.BoolAttribute{
													Computed:    true,
													Description: `Whether the gateway runs the step; true when omitted`,
												},
												"name": schema.StringAttribute{
													Computed:    true,
													Description: `Name of the step, shown in the policy studio`,
												},
												"policy": schema.StringAttribute{
													Computed:    true,
													Description: `Id of a policy plugin deployed on the platform`,
												},
											},
										},
										Description: `Steps run on the response, in order`,
									},
									"selectors": schema.ListNestedAttribute{
										Computed: true,
										NestedObject: schema.NestedAttributeObject{
											Attributes: map[string]schema.Attribute{
												"condition": schema.SingleNestedAttribute{
													Computed: true,
													Attributes: map[string]schema.Attribute{
														"condition": schema.StringAttribute{
															Computed:    true,
															Description: `Condition the request must satisfy`,
														},
														"type": schema.StringAttribute{
															Computed:    true,
															Description: `Kind of selector`,
														},
													},
												},
												"mcp": schema.SingleNestedAttribute{
													Computed: true,
													Attributes: map[string]schema.Attribute{
														"methods": schema.ListAttribute{
															Computed:    true,
															ElementType: types.StringType,
															Description: `MCP methods the flow applies to, such as ` + "`" + `tools/call` + "`" + `; every method when empty`,
														},
														"type": schema.StringAttribute{
															Computed:    true,
															Description: `Kind of selector`,
														},
													},
												},
											},
										},
										Description: `What the flow applies to; a flow without selectors applies to every request`,
									},
									"tags": schema.ListAttribute{
										Computed:    true,
										ElementType: types.StringType,
										Description: `Sharding tags of the gateways the flow runs on; all of them when omitted`,
									},
								},
							},
							MarkdownDescription: `Policy flows of the plan, in execution order, run before the proxy's own on requests the plan` + "\n" +
								`matched. Owned by the manifest like the proxy's flows, and — unlike ` + "`" + `security` + "`" + ` — free to change in` + "\n" +
								`place under the same plan name.`,
						},
						"name": schema.StringAttribute{
							Computed:    true,
							Description: `Name of the plan, the key plan convergence matches on`,
						},
						"security": schema.SingleNestedAttribute{
							Computed: true,
							Attributes: map[string]schema.Attribute{
								"api_key": schema.SingleNestedAttribute{
									Computed: true,
									Attributes: map[string]schema.Attribute{
										"api_key_header": schema.StringAttribute{
											Computed:    true,
											Description: `Name of a custom header carrying the API key; naming one switches the gateway to that header`,
										},
										"propagate_api_key": schema.BoolAttribute{
											Computed:    true,
											Description: `Forward the API key to the upstream server; false when omitted`,
										},
										"source": schema.StringAttribute{
											Computed:    true,
											Description: `Where the gateway reads the API key from`,
										},
										"type": schema.StringAttribute{
											Computed:    true,
											Description: `Type of plan security`,
										},
									},
									Description: `Consumers authenticate with an API key`,
								},
								"key_less": schema.SingleNestedAttribute{
									Computed: true,
									Attributes: map[string]schema.Attribute{
										"type": schema.StringAttribute{
											Computed:    true,
											Description: `Type of plan security`,
										},
									},
									Description: `No consumer authentication`,
								},
								"oauth2": schema.SingleNestedAttribute{
									Computed: true,
									Attributes: map[string]schema.Attribute{
										"provider": schema.StringAttribute{
											Computed:    true,
											Description: `The ` + "`" + `name` + "`" + ` of an ` + "`" + `identityProviders` + "`" + ` entry of this spec`,
										},
										"scopes": schema.ListAttribute{
											Computed:    true,
											ElementType: types.StringType,
											MarkdownDescription: `Scopes required on top of the standard MCP scopes; accepted on a ` + "`" + `GRAVITEE_AM` + "`" + ` provider only, since` + "\n" +
												`the gateway checks them against the Access Management domain. On a plan added after creation the` + "\n" +
												`scopes cannot be registered on the domain and are rejected.`,
										},
										"type": schema.StringAttribute{
											Computed:    true,
											Description: `Type of plan security`,
										},
									},
									MarkdownDescription: `Consumers authenticate with OAuth 2.0 tokens the gateway validates against one of the proxy's identity` + "\n" +
										`providers, named by ` + "`" + `provider` + "`" + `.`,
								},
							},
							Description: `How consumers authenticate against the plan, discriminated by ` + "`" + `type` + "`" + ``,
						},
					},
				},
				MarkdownDescription: `Plans consumers subscribe to, converged by name: a declared plan the proxy does not have is created` + "\n" +
					`and published, a plan the proxy holds in staging is published, a plan the declaration no longer` + "\n" +
					`carries is closed — closing terminates its subscriptions — and a plan cannot be changed in place` + "\n" +
					`under the same name. At least one plan is required.`,
			},
			"proxy": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"server_url": schema.StringAttribute{
						Computed:    true,
						Description: `URL of the upstream MCP server, http or https; the gateway reaches it at runtime`,
					},
				},
				MarkdownDescription: `What a ` + "`" + `PROXY` + "`" + ` fronts: one upstream MCP server and the credential the gateway presents to it. Required when` + "\n" +
					`` + "`" + `mode` + "`" + ` is ` + "`" + `PROXY` + "`" + `, rejected otherwise.`,
			},
			"state": schema.StringAttribute{
				Computed: true,
				MarkdownDescription: `Lifecycle of the proxy on the gateway. ` + "`" + `STARTED` + "`" + ` runs it with the last applied definition and redeploys it` + "\n" +
					`after every apply that changes it; ` + "`" + `STOPPED` + "`" + ` makes the gateway answer 404 and stores changes without` + "\n" +
					`deploying them, which the next ` + "`" + `STARTED` + "`" + ` does. ` + "`" + `STARTED` + "`" + ` when omitted. Reported back as the lifecycle APIM` + "\n" +
					`observes. A start or a deploy the gateway side refuses fails the apply with a ` + "`" + `500` + "`" + ` carrying the technical` + "\n" +
					`code ` + "`" + `gamma.mcp.lifecycle.failed` + "`" + ` and the operation, the proxy and the cause as parameters; the declaration` + "\n" +
					`is stored, and the next apply starts the proxy or redeploys the one APIM reports out of sync.`,
			},
			"studio": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"enable_fga": schema.BoolAttribute{
						Computed: true,
						MarkdownDescription: `Inserts the platform's fine-grained authorization flow, which runs the ` + "`" + `authz-pep` + "`" + ` policy on` + "\n" +
							`` + "`" + `tools/call` + "`" + ` with the called tool as the resource; ` + "`" + `false` + "`" + ` removes it. That flow belongs to the` + "\n" +
							`platform: ` + "`" + `flows` + "`" + ` may not carry an ` + "`" + `authz-pep` + "`" + ` step themselves, and the state reports the declared` + "\n" +
							`flows without it.`,
					},
					"tools": schema.ListNestedAttribute{
						Computed: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"alias": schema.StringAttribute{
									Computed: true,
									MarkdownDescription: `Name the studio exposes the tool under, when the runtime name collides with another tool's or reads` + "\n" +
										`better renamed; effective names must be unique across the studio`,
								},
								"entity_id": schema.StringAttribute{
									Computed:    true,
									Description: `Composed entity id of the tool, the name an authorization policy references, e.g. ` + "`" + `mcp-tool.github.create_issue` + "`" + ``,
								},
								"server": schema.StringAttribute{
									Computed:    true,
									Description: `HRID of the ` + "`" + `catalog/mcp-servers` + "`" + ` resource of this environment the tool comes from`,
								},
								"tool": schema.StringAttribute{
									Computed:    true,
									Description: `Runtime name of the tool, as the server's state lists it under ` + "`" + `tools` + "`" + ``,
								},
							},
						},
						MarkdownDescription: `The tools the studio exposes, each named by the catalog server it comes from and its runtime name.` + "\n" +
							`Every server named here needs an ` + "`" + `upstreamAuth` + "`" + ` entry. On a studio created with a ` + "`" + `GRAVITEE_AM` + "`" + `` + "\n" +
							`provider, a tool added after creation is served but not registered as a scope on the Access` + "\n" +
							`Management domain; the apply reports it as a warning.`,
					},
				},
				MarkdownDescription: `What a ` + "`" + `STUDIO` + "`" + ` exposes: tools picked from catalog MCP servers of the environment, the credential the` + "\n" +
					`gateway presents to each of those servers, and whether the platform's fine-grained authorization runs on` + "\n" +
					`tool calls. Tools converge as a set — adding, removing or re-aliasing one replaces the studio's tool` + "\n" +
					`surface — and ` + "`" + `upstreamAuth` + "`" + ` converges per server.`,
			},
		},
	}
}

func (r *McpProxyDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*ApimProviderConfigureData)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *ApimProviderConfigureData, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.EnvironmentID = providerData.EnvironmentID
	r.OrganizationID = providerData.OrganizationID
	r.client = providerData.SDKClient
}

func (r *McpProxyDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *McpProxyDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	if (data.EnvironmentID.IsNull() || data.EnvironmentID.IsUnknown()) && !r.EnvironmentID.IsUnknown() {
		data.EnvironmentID = r.EnvironmentID
	}

	if (data.OrganizationID.IsNull() || data.OrganizationID.IsUnknown()) && !r.OrganizationID.IsUnknown() {
		data.OrganizationID = r.OrganizationID
	}

	request, requestDiags := data.ToOperationsGetAimMcpProxyRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.MCPProxies.Get(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.AimMcpProxyState != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedAimMcpProxyState(ctx, res.AimMcpProxyState)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
