// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6f2b128fad5f

package provider

import (
	"context"
	tfTypes "github.com/gravitee-io/terraform-provider-apim/internal/provider/types"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/operations"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *PortalListingResourceModel) RefreshFromSharedPortalListingState(ctx context.Context, resp *shared.PortalListingState) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Apis = []tfTypes.PortalListingAPIEntry{}

		for _, apisItem := range resp.Apis {
			var apis tfTypes.PortalListingAPIEntry

			apis.APIHrid = types.StringValue(apisItem.APIHrid)
			apis.Location = types.StringValue(apisItem.Location)
			apis.Order = types.Int64PointerValue(apisItem.Order)

			r.Apis = append(r.Apis, apis)
		}
		r.EnvironmentID = types.StringPointerValue(resp.EnvironmentID)
		r.Hrid = types.StringValue(resp.Hrid)
		r.ID = types.StringPointerValue(resp.ID)
		r.OrganizationID = types.StringPointerValue(resp.OrganizationID)
		r.PortalHrid = types.StringPointerValue(resp.PortalHrid)
	}

	return diags
}

func (r *PortalListingResourceModel) ToOperationsCreateOrUpdatePortalListingRequest(ctx context.Context) (*operations.CreateOrUpdatePortalListingRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var portalHrid string
	portalHrid = r.PortalHrid.ValueString()

	portalListingSpec, portalListingSpecDiags := r.ToSharedPortalListingSpec(ctx)
	diags.Append(portalListingSpecDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.CreateOrUpdatePortalListingRequest{
		OrganizationID:    organizationID,
		EnvironmentID:     environmentID,
		PortalHrid:        portalHrid,
		PortalListingSpec: *portalListingSpec,
	}

	return &out, diags
}

func (r *PortalListingResourceModel) ToOperationsDeletePortalListingRequest(ctx context.Context) (*operations.DeletePortalListingRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var portalHrid string
	portalHrid = r.PortalHrid.ValueString()

	var hrid string
	hrid = r.Hrid.ValueString()

	out := operations.DeletePortalListingRequest{
		OrganizationID: organizationID,
		EnvironmentID:  environmentID,
		PortalHrid:     portalHrid,
		Hrid:           hrid,
	}

	return &out, diags
}

func (r *PortalListingResourceModel) ToOperationsGetPortalListingRequest(ctx context.Context) (*operations.GetPortalListingRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var portalHrid string
	portalHrid = r.PortalHrid.ValueString()

	var hrid string
	hrid = r.Hrid.ValueString()

	out := operations.GetPortalListingRequest{
		OrganizationID: organizationID,
		EnvironmentID:  environmentID,
		PortalHrid:     portalHrid,
		Hrid:           hrid,
	}

	return &out, diags
}

func (r *PortalListingResourceModel) ToSharedPortalListingSpec(ctx context.Context) (*shared.PortalListingSpec, diag.Diagnostics) {
	var diags diag.Diagnostics

	var hrid string
	hrid = r.Hrid.ValueString()

	apis := make([]shared.PortalListingAPIEntry, 0, len(r.Apis))
	for apisIndex := range r.Apis {
		var apiHrid string
		apiHrid = r.Apis[apisIndex].APIHrid.ValueString()

		var location string
		location = r.Apis[apisIndex].Location.ValueString()

		order := new(int64)
		if !r.Apis[apisIndex].Order.IsUnknown() && !r.Apis[apisIndex].Order.IsNull() {
			*order = r.Apis[apisIndex].Order.ValueInt64()
		} else {
			order = nil
		}
		apis = append(apis, shared.PortalListingAPIEntry{
			APIHrid:  apiHrid,
			Location: location,
			Order:    order,
		})
	}
	out := shared.PortalListingSpec{
		Hrid: hrid,
		Apis: apis,
	}

	return &out, diags
}
