// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6dd876308f89

package provider

import (
	"context"
	tfTypes "github.com/gravitee-io/terraform-provider-apim/internal/provider/types"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/operations"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *PortalResourceModel) RefreshFromSharedPortalState(ctx context.Context, resp *shared.PortalState) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.EnvironmentID = types.StringPointerValue(resp.EnvironmentID)
		r.Hrid = types.StringValue(resp.Hrid)
		r.ID = types.StringPointerValue(resp.ID)
		r.Name = types.StringValue(resp.Name)
		r.Navigation = []tfTypes.PortalNavigationPath{}

		for _, navigationItem := range resp.Navigation {
			var navigation tfTypes.PortalNavigationPath

			navigation.DisplayName = types.StringPointerValue(navigationItem.DisplayName)
			navigation.Path = types.StringValue(navigationItem.Path)

			r.Navigation = append(r.Navigation, navigation)
		}
		r.OrganizationID = types.StringPointerValue(resp.OrganizationID)
	}

	return diags
}

func (r *PortalResourceModel) ToOperationsCreateOrUpdatePortalRequest(ctx context.Context) (*operations.CreateOrUpdatePortalRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	portalSpec, portalSpecDiags := r.ToSharedPortalSpec(ctx)
	diags.Append(portalSpecDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.CreateOrUpdatePortalRequest{
		OrganizationID: organizationID,
		EnvironmentID:  environmentID,
		PortalSpec:     *portalSpec,
	}

	return &out, diags
}

func (r *PortalResourceModel) ToOperationsDeletePortalRequest(ctx context.Context) (*operations.DeletePortalRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var hrid string
	hrid = r.Hrid.ValueString()

	out := operations.DeletePortalRequest{
		OrganizationID: organizationID,
		EnvironmentID:  environmentID,
		Hrid:           hrid,
	}

	return &out, diags
}

func (r *PortalResourceModel) ToOperationsGetPortalRequest(ctx context.Context) (*operations.GetPortalRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var hrid string
	hrid = r.Hrid.ValueString()

	out := operations.GetPortalRequest{
		OrganizationID: organizationID,
		EnvironmentID:  environmentID,
		Hrid:           hrid,
	}

	return &out, diags
}

func (r *PortalResourceModel) ToSharedPortalSpec(ctx context.Context) (*shared.PortalSpec, diag.Diagnostics) {
	var diags diag.Diagnostics

	var hrid string
	hrid = r.Hrid.ValueString()

	var name string
	name = r.Name.ValueString()

	navigation := make([]shared.PortalNavigationPath, 0, len(r.Navigation))
	for navigationIndex := range r.Navigation {
		var path string
		path = r.Navigation[navigationIndex].Path.ValueString()

		displayName := new(string)
		if !r.Navigation[navigationIndex].DisplayName.IsUnknown() && !r.Navigation[navigationIndex].DisplayName.IsNull() {
			*displayName = r.Navigation[navigationIndex].DisplayName.ValueString()
		} else {
			displayName = nil
		}
		navigation = append(navigation, shared.PortalNavigationPath{
			Path:        path,
			DisplayName: displayName,
		})
	}
	out := shared.PortalSpec{
		Hrid:       hrid,
		Name:       name,
		Navigation: navigation,
	}

	return &out, diags
}
