// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 41a349e01d19

package provider

import (
	"context"
	"fmt"
	tfTypes "github.com/gravitee-io/terraform-provider-apim/internal/provider/types"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"regexp"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &PortalListingDataSource{}
var _ datasource.DataSourceWithConfigure = &PortalListingDataSource{}

func NewPortalListingDataSource() datasource.DataSource {
	return &PortalListingDataSource{}
}

// PortalListingDataSource is the data source implementation.
type PortalListingDataSource struct {
	// Provider configured SDK client.
	client *sdk.GraviteeApim

	// environment ID
	EnvironmentID types.String `tfsdk:"environment_id"`

	// organization ID
	OrganizationID types.String `tfsdk:"organization_id"`
}

// PortalListingDataSourceModel describes the data model.
type PortalListingDataSourceModel struct {
	Apis           []tfTypes.PortalListingAPIEntry `tfsdk:"apis"`
	EnvironmentID  types.String                    `tfsdk:"environment_id"`
	Hrid           types.String                    `tfsdk:"hrid"`
	ID             types.String                    `tfsdk:"id"`
	OrganizationID types.String                    `tfsdk:"organization_id"`
	PortalHrid     types.String                    `tfsdk:"portal_hrid"`
}

// Metadata returns the data source type name.
func (r *PortalListingDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_portal_listing"
}

// Schema defines the schema for the data source.
func (r *PortalListingDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "PortalListing DataSource",

		Attributes: map[string]schema.Attribute{
			"apis": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"api_hrid": schema.StringAttribute{
							Computed:    true,
							Description: `Human-readable ID of the API to publish`,
						},
						"location": schema.StringAttribute{
							Computed: true,
							MarkdownDescription: `The path in the portal's navigation where this API should appear.` + "\n" +
								`Must match a path defined in the Portal's navigation for the API to be visible.`,
						},
						"order": schema.Int64Attribute{
							Computed: true,
							MarkdownDescription: `Display order of this API relative to its siblings at the same location.` + "\n" +
								`Disambiguates ordering when APIs from multiple listings share a location.`,
						},
					},
				},
				Description: `List of APIs to publish to the portal. Use each entry's order to control display order relative to siblings at the same location.`,
			},
			"environment_id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: `The environment ID.`,
			},
			"hrid": schema.StringAttribute{
				Required:    true,
				Description: `A unique human readable id identifying this resource`,
				Validators: []validator.String{
					stringvalidator.UTF8LengthAtMost(256),
					stringvalidator.RegexMatches(regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9_-]+[a-zA-Z0-9]$`), "must match pattern "+regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9_-]+[a-zA-Z0-9]$`).String()),
				},
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Description: `Resource UUID.`,
			},
			"organization_id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: `The organization ID.`,
			},
			"portal_hrid": schema.StringAttribute{
				Required:    true,
				Description: `The HRID of the portal this listing belongs to.`,
			},
		},
	}
}

func (r *PortalListingDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*ApimProviderConfigureData)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *ApimProviderConfigureData, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.EnvironmentID = providerData.EnvironmentID
	r.OrganizationID = providerData.OrganizationID
	r.client = providerData.SDKClient
}

func (r *PortalListingDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *PortalListingDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	if (data.EnvironmentID.IsNull() || data.EnvironmentID.IsUnknown()) && !r.EnvironmentID.IsUnknown() {
		data.EnvironmentID = r.EnvironmentID
	}

	if (data.OrganizationID.IsNull() || data.OrganizationID.IsUnknown()) && !r.OrganizationID.IsUnknown() {
		data.OrganizationID = r.OrganizationID
	}

	request, requestDiags := data.ToOperationsGetPortalListingRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.PortalListings.Get(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.PortalListingState != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedPortalListingState(ctx, res.PortalListingState)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
