// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7861a4c1da39

package provider

import (
	"context"
	"encoding/json"
	"github.com/gravitee-io/terraform-provider-apim/internal/provider/customtypes"
	"github.com/gravitee-io/terraform-provider-apim/internal/provider/typeconvert"
	tfTypes "github.com/gravitee-io/terraform-provider-apim/internal/provider/types"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/operations"
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *SubscriptionDataSourceModel) RefreshFromSharedSubscriptionState(ctx context.Context, resp *shared.SubscriptionState) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.APIHrid = types.StringPointerValue(resp.APIHrid)
		r.ApplicationHrid = types.StringValue(resp.ApplicationHrid)
		if resp.ConsumerConfiguration == nil {
			r.ConsumerConfiguration = nil
		} else {
			r.ConsumerConfiguration = &tfTypes.SubscriptionConsumerConfiguration{}
			r.ConsumerConfiguration.Channel = types.StringPointerValue(resp.ConsumerConfiguration.Channel)
			if resp.ConsumerConfiguration.EntrypointConfiguration == nil {
				r.ConsumerConfiguration.EntrypointConfiguration = jsontypes.NewNormalizedNull()
			} else {
				entrypointConfigurationResult, _ := json.Marshal(resp.ConsumerConfiguration.EntrypointConfiguration)
				r.ConsumerConfiguration.EntrypointConfiguration = jsontypes.NewNormalizedValue(string(entrypointConfigurationResult))
			}
			r.ConsumerConfiguration.EntrypointID = types.StringValue(resp.ConsumerConfiguration.EntrypointID)
		}
		endingAtValuable, endingAtDiags := customtypes.RFC3339Type{}.ValueFromString(ctx, types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.EndingAt)))
		diags.Append(endingAtDiags...)
		r.EndingAt = endingAtValuable.(customtypes.RFC3339)
		r.EnvironmentID = types.StringPointerValue(resp.EnvironmentID)
		r.Hrid = types.StringValue(resp.Hrid)
		r.ID = types.StringPointerValue(resp.ID)
		if len(resp.Metadata) > 0 {
			r.Metadata = make(map[string]types.String, len(resp.Metadata))
			for key, value := range resp.Metadata {
				r.Metadata[key] = types.StringValue(value)
			}
		}
		r.OrganizationID = types.StringPointerValue(resp.OrganizationID)
		r.PlanHrid = types.StringValue(resp.PlanHrid)
		r.StartingAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.StartingAt))
	}

	return diags
}

func (r *SubscriptionDataSourceModel) ToOperationsGetAPISubscriptionRequest(ctx context.Context) (*operations.GetAPISubscriptionRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var apiHrid string
	apiHrid = r.APIHrid.ValueString()

	var hrid string
	hrid = r.Hrid.ValueString()

	out := operations.GetAPISubscriptionRequest{
		OrganizationID: organizationID,
		EnvironmentID:  environmentID,
		APIHrid:        apiHrid,
		Hrid:           hrid,
	}

	return &out, diags
}
