// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1ac280ae3ce5

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AimMcpProxyStateProxy struct {
	ServerURL    types.String                   `tfsdk:"server_url"`
	UpstreamAuth *AimMcpProxyUpstreamAuthOutput `tfsdk:"upstream_auth"`
}
