// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3b96426e387f

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AimMcpProxyFlowExecution struct {
	MatchRequired types.Bool   `tfsdk:"match_required"`
	Mode          types.String `tfsdk:"mode"`
}
