// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e00df5e79f96

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AimCatalogMcpServerNoAuth struct {
	Type types.String `tfsdk:"type"`
}
