// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 89ae0aa05c2a

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AimMcpProxyOAuth2PlanSecurity struct {
	Provider types.String   `tfsdk:"provider"`
	Scopes   []types.String `tfsdk:"scopes"`
	Type     types.String   `tfsdk:"type"`
}
