// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 66bf2e0bc04a

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AimMcpProxyStudioUpstreamAuth1 struct {
	Auth   *AimMcpProxyUpstreamAuthOutput `tfsdk:"auth"`
	Server types.String                   `tfsdk:"server"`
}
