// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type APIResource struct {
	Configuration Configuration `tfsdk:"configuration"`
	Enabled       types.Bool    `tfsdk:"enabled"`
	Name          types.String  `tfsdk:"name"`
	Type          types.String  `tfsdk:"type"`
}
