// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 322b847c657b

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type APIV4StateConsoleNotification struct {
	Events []types.String `tfsdk:"events"`
	Groups []types.String `tfsdk:"groups"`
}
