// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 482f98e89ae3

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type APIV4SpecConsoleNotification struct {
	Events []types.String `tfsdk:"events"`
	Groups []types.String `tfsdk:"groups"`
}
