// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 147e6dbff642

package types

import (
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
)

type ApplicationSettings struct {
	App   jsontypes.Normalized    `tfsdk:"app"`
	Oauth jsontypes.Normalized    `tfsdk:"oauth"`
	TLS   *ApplicationTLSSettings `tfsdk:"tls"`
}
