// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5f3d0aac9070

package types

type ApplicationTLSSettings struct {
	ClientCertificates []ClientCertificate `tfsdk:"client_certificates"`
}
