// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a9ece6be2196

package types

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/provider/customtypes"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ClientCertificate struct {
	Content  customtypes.TrimmedString `tfsdk:"content"`
	EndsAt   types.String              `tfsdk:"ends_at"`
	Name     types.String              `tfsdk:"name"`
	StartsAt types.String              `tfsdk:"starts_at"`
}
