// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: fbc366291a54

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type DictionaryTrigger struct {
	Rate types.Int64  `tfsdk:"rate"`
	Unit types.String `tfsdk:"unit"`
}
