// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Dlq struct {
	Endpoint types.String `tfsdk:"endpoint"`
}
