// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type EncryptedProperty1 struct {
	Key types.String `tfsdk:"key"`
}
