// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Entrypoint struct {
	Configuration jsontypes.Normalized `tfsdk:"configuration"`
	Dlq           *Dlq                 `tfsdk:"dlq"`
	Qos           types.String         `tfsdk:"qos"`
	Type          types.String         `tfsdk:"type"`
}
