// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6abd4e35af86

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type GroupDefaultMemberRoles struct {
	API         types.String `tfsdk:"api"`
	APIProduct  types.String `tfsdk:"api_product"`
	Application types.String `tfsdk:"application"`
}
