// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type HTTPListener struct {
	Cors        *Cors          `tfsdk:"cors"`
	Entrypoints []Entrypoint   `tfsdk:"entrypoints"`
	Paths       []PathV4       `tfsdk:"paths"`
	Servers     []types.String `tfsdk:"servers"`
	Type        types.String   `tfsdk:"type"`
}
