// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type Listener struct {
	HTTP         *HTTPListener         `queryParam:"inline" tfsdk:"http" tfPlanOnly:"true"`
	Kafka        *KafkaListener        `queryParam:"inline" tfsdk:"kafka" tfPlanOnly:"true"`
	Subscription *SubscriptionListener `queryParam:"inline" tfsdk:"subscription" tfPlanOnly:"true"`
	TCP          *TCPListener          `queryParam:"inline" tfsdk:"tcp" tfPlanOnly:"true"`
}
