// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5ed4c9ef5f5d

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type LoadBalancer struct {
	Type types.String `tfsdk:"type"`
}
