// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5f93ee3578a5

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type LoggingModeV4 struct {
	Endpoint   types.Bool `tfsdk:"endpoint"`
	Entrypoint types.Bool `tfsdk:"entrypoint"`
}
