// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3c5f12ab2e9e

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type OtelLogsV4 struct {
	Enabled types.Bool `tfsdk:"enabled"`
}
