// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6f7a42b60609

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ResponseTemplate struct {
	Body                    types.String            `tfsdk:"body"`
	Headers                 map[string]types.String `tfsdk:"headers"`
	PropagateErrorKeyToLogs types.Bool              `tfsdk:"propagate_error_key_to_logs"`
	Status                  types.Int64             `tfsdk:"status"`
}
