// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a10f21cabd28

package types

import (
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ServiceV4 struct {
	Configuration         jsontypes.Normalized `tfsdk:"configuration"`
	Enabled               types.Bool           `tfsdk:"enabled"`
	OverrideConfiguration types.Bool           `tfsdk:"override_configuration"`
	Type                  types.String         `tfsdk:"type"`
}
