// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type SubscriptionListener struct {
	Entrypoints []Entrypoint   `tfsdk:"entrypoints"`
	Servers     []types.String `tfsdk:"servers"`
	Type        types.String   `tfsdk:"type"`
}
