// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package globals

import (
	"github.com/gravitee-io/terraform-provider-apim/internal/sdk/internal/utils"
)

type Globals struct {
	// environment ID
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
	// organization ID
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
}

func (g Globals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *Globals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Globals) GetEnvironmentID() *string {
	if o == nil {
		return nil
	}
	return o.EnvironmentID
}

func (o *Globals) GetOrganizationID() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}
