name: docker-cache-restore
description: Restore Docker images from cache
inputs:
  cache-key:
    description: Cache key to restore
    required: true
  cache-path:
    description: Path to the tar file
    required: false
    default: /tmp/docker-images.tar
outputs:
  cache-hit:
    description: Whether the cache was hit
    value: ${{ steps.docker-cache.outputs.cache-hit }}
runs:
  using: 'composite'
  steps:
    - name: Restore Docker image cache
      id: docker-cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ inputs.cache-key }}
    - name: Load Docker images from cache
      if: steps.docker-cache.outputs.cache-hit == 'true'
      shell: bash
      run: docker load -i ${{ inputs.cache-path }}
